{
  "compatibilityLevel": 1606,
  "model": {
    "culture": "en-US",
    "sourceQueryCulture": "en-US",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "annotations": [
      {
        "name": "PBI_TimeIntelligenceEnabled",
        "value": "0"
      }
    ],
    "tables": [
      {
        "name": "customers",
        "description": "Customer records in the fictionalized 2023 case-study snapshot.",
        "lineageTag": "05891732-bced-4472-9f3f-4e592fa42976",
        "columns": [
          {
            "name": "id",
            "dataType": "int64",
            "sourceColumn": "id",
            "summarizeBy": "none",
            "lineageTag": "51ecb799-13cd-44ec-bede-99024b9f0206",
            "isHidden": true
          },
          {
            "name": "name",
            "dataType": "string",
            "sourceColumn": "name",
            "summarizeBy": "none",
            "lineageTag": "da3c9709-cf07-42c9-bdc0-7e7bfe00a229"
          },
          {
            "name": "country",
            "dataType": "string",
            "sourceColumn": "country",
            "summarizeBy": "none",
            "lineageTag": "90e4d633-8a5d-4493-af6d-b3b973d49b7f",
            "dataCategory": "Country"
          },
          {
            "name": "city",
            "dataType": "string",
            "sourceColumn": "city",
            "summarizeBy": "none",
            "lineageTag": "df2536bf-b6e9-4890-b4d5-9f1ca3e0cfab",
            "dataCategory": "City"
          }
        ],
        "partitions": [
          {
            "name": "customers",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRecords(Json.Document(Binary.Decompress(Binary.FromText(\"pZ3NcuM6c4ZvBTWbbM6pGomyRz47Sf6bsWQ7ljOuM6ksWmRbhAUCLpC0R5PKBeQyvvr2uYLszo2lIOkYTQAmSGfpmeJTJPiiAXS/bP37f37i2ac/jge/fZJQ4Kc/Pl1AxVGyKyhW8Om3T6mqZaW3n/749G/LifmbV+aPuap5+cKFwE//9duBMXxjfAOJbFnwKm8QZiAhAwu5V1rJSllC8kaYgRaqZAvQFZf4q4FZ4E+eKovZ/81m5q831OgNNdlwDeweJGyaD/QNnkHSu9lsyb0cWYCUwBZ//a8QqBuAC9QFyK1FTFELLi3j+I2xAM2BLbl4ad7DVMMvLixh+dc/FbuFWpA7+fJG+ZGDXLMH5M1hzbkEehP8icu1vX78dv0cag3sTpVlk/C1AkEe404V5LWevF1+Ci88Y1OtXmVTGVdUGDJTdgi+fH67+paj1shO62clq8b15xpkipZxC5qXFmG1+XWtNLvFSquXBuCuLktOhmChylS9WoJV5iQvMGOXUJbQfIaz9fa5soQZcG1fwRcrzFvNt8Cu6gKaWvgqs8Yd1MUKuAVYOS5BQ86+qVyWqnkLk7qsNAiKWW4ziVbVX6wov9Ug2Vw9O3Njotcoq6YeapSqZBOukQyqleYVL9hSqd+36NzPUtVVzq6URnpHqGphMVab51DxAthE/H6Vg+CPTvCYnFnGad0YG6vPO7VCXbEHLtyxcYJPySZyjYI+kJXpvE637OwFZPmuShcg0xzLCvUbYGyV+rWEFQoB7AJ0ypsPsnwGLiko0zyzEKvVicCfyNnXF5ARtS6By8rIGnW5qrWduWOr26V6zjmyOT7ii8bW2TPfkvk3tso9K4qOYWxRS57mljEii8NKcxRsCbJSzeF1I9kdVyxDZpYCOpXGVsIPJpjNW2PZ0gS8nIhlTHSrnji7hg0UtW4N7DelifxvhC/kFfG0yzr1HWSq6hcqFqvZS5AlW6Z5wbOqfVgvoWi+3hOyYBZYspkAvXlf9rOcp7C2Q3niKRbZwszWulUf1zy10f2ECJaXObDJKquFcDQPdcbZRMOKyvaObyGzKjmxYl3wNAcUwSDXeKJLVZcVUetJQqfPE8hMK3ZX88j6r2RllhYbJ0+sYm/EGswr1lI5S687Da/gF5BbsTq9hgrM0NxChaIt6J+iyK1UT6xU5wg5u1Mr3iXmL1CsVK0leUlWsmdZDTpT7ELJX2DinzN5BNK4IiveEMzYjSffUJbYvKNTlMVBhgfZqWeUOayRDI5V7r0qoPzFrtQriHLTnMy3SoDMLOkBdAl2WR58tgJeqBzMyrwEnrWtyyaqGllwIJgBWVyLGgWbga6cIEej/5Trgpu4UhDIkARKLrbsQiO2SHcJku1mFi9TRTBkpwArodiNrnDduoRMQacolKRPRCKuhhTZfa6KZ1c71/jKfiA0x3hSp5vdv1iYVbLZhZZKsO+g1+BoRwlVNOb3VK1V9dc/CMgK+qZMQbM7KLh2NiC3qGuyFvGCPpbV8Ve51jwzEQJk6T7Y8hUzJCO0rFS6yZWgr4sEYDR62JjF5rvmzpS4xipHbQakJGNUmJU/a7z+E/LelFDsjqdp6yZ5wQUJF4PBZ1eEgX0yFdCCQ8HJ9VbEcy4zYLfoDq0b9y5qyEDAE2gyxgOr4z9VXZb4yCai+SALpVVKQTMoYSVAppRjhfwDuITV3ytDc6ls7Osmq5qd5rCij2WVPMs1L0P7ssa0QqgqcqgcDKx6z7mSwG7+ZaakVM7uW2NzGpzWK3oSGwzIUQxzs5qpGrLmuNzXkjdWhN0/EIaVr5mPUJqzTM2dbRCKNa8LMo20eQuCcsaNCQnsoq52Z6Pm6/6OEn/VKIC+KA0pUJSV7bLCR5DsWr1Acw8x0woq+lg/YK1xZSFDK905aGBfVxpyXjQgc1yBVDRqIdd1RSBWv2dVDjK++Jvw9afSG8Jw9rsQm0MBREKmERTmKCE4FC2KCzDo7oG/cGDflMR+CBpzSyVDJ4kYwir27Tyy4N7mPXowGgytbOd1alQLL7zlacIQq9lJgYKbLEKm+bp2RNuBZCU7eUG9Ded44pzEqna/e75ELUFm/UEDEqJM2qmqMHgEfT/LMUiscqcon6Dgki2Uck5qrQQr3EvQz6jZPWyFen8T4wGsas9eUGwlm8gMda+nIOkFSDdsH+W6X24Ve60gZw85r94fgMARfJBYqS44sDn2vLyxKdBbdglau1KPMaw89wfmnTp7IUZWmWeCP0Ee3r5FMQM/APgnxFhOdTAaNiPiHF+dIYkjktAMAbFxYlEcNHLC4p+qluuejCN3kbgEIXoyjkkMMjkr4Wz14xmAwcgNq1c88ighyLgh+GWqqqo348RZef2TSwfK0WcnLE8yd9nsQhk0Q8AUXI3Ek5yDo2FzCh7Our96c5y9gL+j7gLxNgOX3JFbF4q7HwgdnbpwjgMzcQbFswkP/RMLgyNXxAtepfkHWWM/Xu0TuuVHaCeNKXpv/jeqpADn+LMbLm5zsyd8/shNHTvyvgXt6jtWExocO+r2D0RxhCPss+wVdNYX4gl7poTgve/FVfaywlfQkVSoRwnperlbFH+1k5xc9eDYU7Ty9gBxSFDKa9R9OU0R3yFm/QBfPPXOlNr0ZDiiXSi9dopf7QW4wRdHslM3QMSud/S6qPVzvu1F8MQ6BS6wH8OLwfwFncpBDBEMv0o9O0GgtSQz+OJK9M7ky3XmbhAjlIBGZ+pnH0JTnZfKRJEe1489cT70BDjKDC2KHQrkg7GrT63Upr06FcQ4Ml3C7gDVn+OJ9VbzFPtzXMFOUUp0NoidQCHZPiiVtZLeKeANxq58p6Dd9EhnVjDQlh+EOXrG0Pm3K+wkEHkFFvBBmqP0byg37lLbakcZnDgav0Wtt32udzfD6tWN4hGAp+q5cg48EYAr51uoKv8FRSAhKV/W6xxbB7NZAh6cuBI+F0r3IwSEe65Kt+oUgTQFG4o3rYDhZ0+kS14Uql1YLoNUgE2G3zi/wFkWr/kaNd0bz2GtSsKw4jzYQBZ12RNBcwxcYlazmw08OgmwKIXYvgou91sV1Q9hZXpIhLNdcbJw9m5RDskxZPgKAoMpcQ8zWdVP9PUQ99e+DhNKz0cpYzJ561cosZbsRsATz7Af6IS+pgIKMLWqs1/9KKRYtjdk/V1b4v0wVrpXr1AgW6AsnQLVRQ7UUDJJU00JxBm2UWUNbFKCdLKWEYQV7p/wym5Kx50XudoK9ko9cnbzWpd1n+uJTbEAtkT9CtDnepKzBTNfFGy2rY9vrG8lJwRiTig5u9qixgIqJwMVg4zJMDwpdr0FvVG9CCSWPnJgk0wVfa4nRTDzGqfKPMK6F4FUcFFDpdh1JtRL823uPXWTR81TgtqVwSU23V9DWg7jz7liiyrHKn+FjxOtVu9zWCl2Kkypgn8caOV7rYoS2FVeF+BE3F5AYrvZqJKzH7X4f4wgicHbXaS6TusVduDN4BnZvSk+WhgpToDMeAlsobZdHjUEI1Ycngtku6f9IMtKf6rkGiTvrrwAjhTW5rVcc+Mqg1yAXH8UaCfGN1Xic84WdVU3VXyFckso18Z+S3wEQ1JgewD5xHXNFq8g17wfxerf7HJqtqjXqh+BCP4JNWcPxtTX8y5omc1ULm+M477nfVhlf6sLYDdpzt145TAWqlhBSWI/qbbtvX8BW3SUQXQMwjiJXQNXlHDibnCWOWj+2AtCSm4TwU3ZAXTrS/EJjW0wCnYHuXvaa/WID0mhbT+QbKHKChwjdIRhBXoOlckOi9+XsMVWT5zLIEW2w8bVswBFCHRTYT6euDQWFt5rMIhXrADNDl6kNkLA2jckRbYliFdTjl1n294UsrsAzQt2Dxo3vSknZFzNFyGQF6ru61YckkLbPRSo2TlUee9HIoW2SQGZqtnU2RagxDWQ1MSpmRME0DiyqZqdcvXcj2C1ejiSALvOODjbxyiGHNlejeW+7/VWrLMc+SZny20/ALGGGZUCm/GyjNzEvapX9HXQvYHmUAA7jz6IyxjTCKRqAVtkpxzcA2yUY3V6neEW2UWNPW+FFM2ucsj4k0lOONmiKMMqdDf5Vf3IZqoWfHWwUb6Rvr4ovWUzBSUV/YpnT8RgOSR1s93RvgJ2pSR+hJQ01qxHdq/Btep0JI2ak6gwd3XKQTv5k440q+Sp+frOJITW8LEbO26uAZixBfB1h7uaqho2SEhW2bsD4imHVYfX52HoR2hlaVIz3d6eBzpphItz9Xg4lPXDkMKaMToAu6mhqty8VzcUETrkW5NzksH1rovvdkhqbXPkwmzKsgyyD4DItxS7HMtU1ZschLMf6cayOv8BuTZpgjoTID5AOnKW4jPBFiBLVev+JuUhqccd8o6722sHLcz03CApkQ5JRe4O0pxnbFJokJE7CoGszK+V+dbyrCzh8QMc19PT30079Mtzfd20wzE1pXdy04YclkNSn+tmqA1TErLGdvHUut9LDUlhrs1SG7OPDUlh7j1HbZxBUhNthtq46WpIv2h731HbBWTV22qpfd8DOhzT/PDHzLRDUnrraKYN2CeHpOTWzVAbhJCqW4upNu7cGpL623ve2i4Umm8LWmw7GZmGtBYXMNp2hFgJv2u3jTl/hvTbtnf8tnGG1W2b4TbmlBmSelyL4zaGSUhV7h3HbbvNJPkcdKT7ftsYZugETN9t2+rPSEhN7j2rbQRAznZBn21b44HksxtmPYdt++XHDY373trWD7oSUnh7z1YbAYydsOw7ajuYNxJScXvHUtuFQipu73tqO7oZkoGzLfCNtZ1J3s7Ac9d26faRDNy9QchK1I00Csy9oMM2/hlyMnAVHLTXdgEFPgYKeWu75uSTwZfGzAzYa7ujxm6UCDpse9RtkoGj+YDPtg9u6Ijft9y2d+9Iho7gQ4bbGMJTeshu2/pBeTJ0VR7y2kYQIXmHjLatNpxk6Anbd9lGCEFFexbbVu9KMmyq2PPXRq72hOuZayOtdZKhI9SAtzaGSBxxeubaWEuMJHHUGbDXxhmePAMG20ibnSTxorDvsI0ygvHXt9h2bqKSJK5W37Hb9iAGtOtab9v7xCRJU7kB720M4InXM99G+wwkiSPf0KoZp4xcBfv221ulq7qRLZ7zckW3iiNHxCEzXAeKJ2PfeutTzL+Q0DRyZRzy3cYpISF7ptuu/ZqSkavigOu2OywYfMsobaZ0plb01TsyDlpuO4ECsdi328YanCQjR9Ahn20UcuTo2bfamg0Of37mhxfwlj/ggjzSkbtL9h233Tiepj3jbbdOIMmRK+ywA7crLSTwgBU3iHtAs/lZ0+Y/yZEr8YArtzvMSnx/fPtAJ4CElPUOqjS5m3552ITU9XY6CH2UHCGcuAoIf9odS6EmpK63F0D4w+Q4Z9CY9sHORq2p2IRU8/bv2s9NRACkvLHPn0a6Z7m9phJSvDtkO93kRuT6o4D+vRRFg3GbK5T8J2FYlb6lOh80X+dVH4hV6SHT+aHeRcmxl0bzcw2dOPQTetNKyU+AtXTCSUhpbp9W9DM3rZcP3DnrtRGgV5+CEKSjSkLqb7sVJNIsw7vcynLfuclP+nhDeMqRKrvRK/LddlYxCPlKPgUtsKrYNba3VXR77ySkvLbLWQcOFhEAyaEJBKl0h24fU9WcZ6SmdgrSdB8MZlHaGW7TET9l1Yx6ULLvuKZvlpTTDktJ6FgSpQxo3OvfDDUZ06Su5qaf6kr1Sy+TQtq3Wphmv1NT54l8uudCyOoPhSmidWpO6VJol91KcYnM9KjFyJg0s8yklHZoa9ehC6KDoP6dKudYswuue33NmPjfsmGomhGBOO1H9km+VsACdImNTswJqaBd81QJKM05lvfnELWahs9ovi+KfKUawljN3uem09WWTU0lP48NcIhFvhMSwDWycyUr4LJdd42ml8kJ7UPykxdmFrnVuAiBCPdgz8PdQSHyth3KcXMmsjlq1f5R872qhapLCrHaNUl/dlrrw+64D4Su/SoztwJFVHoBDumjtz/cIJvl+AKCR4pXHmvUaA9p8mrI7lSat7/oqdIZQv2TYKyIv3OZoqzYwvjQ2l9UgGNVfMHVC0jJe7bSHjUKauYrlSk306APYUTXD2AmaaV6XH5EnqHeuw4KkH0IjZ7mqWLnqLVrtm4tjI0+0w68aJzSmTbGT9foGKHQLnpVhcrsetNehBO6O5HQt+fjiBTVdq3RTaJSVq2Ea3imJ6kRKaXtFVimxjT0rEpetT6LB6K+MSV3TWKnum5/tR7E6vM7iH3Shp0iM1LrxSF1XxMZTTZZe3a/JmN32JckOo4G9IDFTWfCmTHU94SQLrzm/36pffNq3TowAQ7pdI4ZmrITu9AQmf4BzthZmpl5Xa0j8x0lbyBI00fUuLOia97+pl0GKYndq6KAUrELrnQWiQUehiQCNAfzQwkmOdWPQTw2u0xNoNrXniAZDT2jQqTNaABBAqvZ21+hEC1HnQDAqvXvCoqfB48xaHA1+ZldYqLlgBFIzoxIUewtufuRjvojUh87FPk+1KlxNHT6MkTyX0GG1+2xZ6/0UbDLYyQx4UMCbR4DvpwIxMtctSeefADp9LjP0/jGmtbU1YiUxPZZig69M32Ia/+KpPB8ALV+mTxRe/LMv95LDPRNnY2SxhZgl6CIZJs8xIgq0yRJopPER3gpq4DdsZ1APo88JCcClo4OybsRKX69JY7i2eb3YH4qK2B66ESihkUBXdJqIQq1hO1/oyBk5WhJL45GNKUlIGjBaL2eemxTtYplotzLydeSCkO2i7araZPH/akVdbBG1pbjHDUKW2Lr2y7arx425suuvqq3IFuG0EMkjV2HX1Vtv3pEwob5QaMHqKLibqZXR6RUdWl2PXl0sQ9ByOlflXkN8QRrAOL4ZwO2jSiC1F5xBWXFQUZzm26ud0SKVMZu+Y7Jop3RqE9VVY6vsX2Yj6DrvFAYslZECM16K2rfWdGWax6RytShHBNoDNROIAv8bkcc9B+2I0h+ap/w9qvP7QDyfYI5wr2yC80fH91WyO3p7tGxV0AN1HSjELIPVWuQoSJzlGHVeWcmiG93iBFIWeprCZDuUi+tQzqpBMgKCKKR/N+ye6Vbx8IHDGnEMJ0UQtaUCIM0AjM/S9Mubv/yRgLKFA9M2n/VL+8/oj9khsaxuUvZ92kqOSLFqb/+2zRQkMhuedqvjDEiFapDOvkCuBB9KVahh1+5M7mxPJaGbaT+R6RGta/smHPKs0nC9OkuOSJ1qst6rdg5rPr8YNho7GxG0VSH1v1ugeSiTNmATTVWvcsGI/rbZfuc9CnKSKkrhLGKPfxsR4f0b4hDf3xPcDQHyDtVt3fcDHFoZN3XvDqUiRqFgxGpV81QGMSu9hB5Sw7DivZf612uz0xlFUn5O4wTf/po2e8+AsWqLvVIv15AqlV/lyS/8wzao0oAY9VrkuNcdixWBUjUb6XXUP80H86mee9KCKlXTTK9D7q7b2FbOX4Jg1St5mAKgnaj1pdEM1W7CtotlGlkrAMYUgqoM43bLqXbAMZK+TtPK6XZNyXa62jLSkNpvmhbEwyNwNJ8Yco11O1DE+AcfW58wKj++p+qU1U7iBqQW6pyLjIM/epQJxRpoCDwJy/ZtYosufNG5Doi5auJBF6yC/P/kVK9g7BKnpqThpFyh0KjSzlqbkK61DxdxDEdjX0RSvWs5x2RStahnNahGuYgaBJrV0PqV9I78qtY/Sp6RwN66DIVvZ6VuKMB3TGYqmbXQtx//B8=\", BinaryEncoding.Base64), Compression.Deflate))),",
                "    Typed = Table.TransformColumnTypes(Source, {{\"id\", Int64.Type}, {\"name\", type text}, {\"country\", type text}, {\"city\", type text}})",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "orders",
        "description": "2023 orders; USD amounts restated at the fixed current FX snapshot, not transaction-date FX.",
        "lineageTag": "99889ba0-8207-479c-9701-92b30cbe8b37",
        "columns": [
          {
            "name": "order_id",
            "dataType": "int64",
            "sourceColumn": "order_id",
            "summarizeBy": "none",
            "lineageTag": "6ded401b-e89d-4461-ba32-18d4d0c52391",
            "isHidden": true
          },
          {
            "name": "customer_id",
            "dataType": "int64",
            "sourceColumn": "customer_id",
            "summarizeBy": "none",
            "lineageTag": "d5cf1f1c-d164-4b91-976b-c6832e1bb606",
            "isHidden": true
          },
          {
            "name": "order_date",
            "dataType": "dateTime",
            "sourceColumn": "order_date",
            "summarizeBy": "none",
            "lineageTag": "d72f1039-c37e-43c6-b2d5-c5c8b8baee84",
            "formatString": "dd MMM yyyy"
          },
          {
            "name": "shipping_date",
            "dataType": "dateTime",
            "sourceColumn": "shipping_date",
            "summarizeBy": "none",
            "lineageTag": "22598488-7fb8-4389-8b8f-45cac050f321",
            "formatString": "dd MMM yyyy"
          },
          {
            "name": "delivery_date",
            "dataType": "dateTime",
            "sourceColumn": "delivery_date",
            "summarizeBy": "none",
            "lineageTag": "92d915e3-7fd4-48be-850f-1dc0cd0e67d3",
            "formatString": "dd MMM yyyy"
          },
          {
            "name": "total_amount",
            "dataType": "double",
            "sourceColumn": "total_amount",
            "summarizeBy": "sum",
            "lineageTag": "3cd5d1fa-12dd-4029-83b9-0f25ca12b786",
            "isHidden": true
          },
          {
            "name": "currency",
            "dataType": "string",
            "sourceColumn": "currency",
            "summarizeBy": "none",
            "lineageTag": "3ee89869-8b06-4909-b5fb-77340f2ee231"
          },
          {
            "name": "order_status",
            "dataType": "string",
            "sourceColumn": "order_status",
            "summarizeBy": "none",
            "lineageTag": "1f15f715-924c-4e34-bc9e-8aae5cf62ace"
          },
          {
            "name": "payment_method",
            "dataType": "string",
            "sourceColumn": "payment_method",
            "summarizeBy": "none",
            "lineageTag": "f09a45a3-d3fe-4939-9880-d3f172373c11"
          },
          {
            "name": "total_amount_usd",
            "dataType": "double",
            "sourceColumn": "total_amount_usd",
            "summarizeBy": "sum",
            "lineageTag": "7fc3ab0c-90b3-4d82-9b1e-c593de545605"
          }
        ],
        "partitions": [
          {
            "name": "orders",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRecords(Json.Document(Binary.Decompress(Binary.FromText(\"5X1tz223jd1fGdzPtsA3kaK/xY7rzCTxGM64zaQoAjd2Z4ImzsB2BgiK/vdCj6+BmpS0z3OkbQ8wXwIYD3BPCHFLi4vkWv/9/7z5y9dffPn17//4xZv38J03f/jrN9/+5c9v/1vxnbd//eLzb798894bAuJ3Ad8FevPOm2/+9Y//9m9//Opf0h/5zTtvvvjyT3/89y+//lv6o7155823f/n28z/9/vM//+WvX3375j2qUGr/5a+//vKrP/ztzXtvPvvNz998/8vffPv5t3/95s17b37+3b/45Rdv3nnzb5//7c9ffvXt7//85bf/+pcv3rz35oOvv/zij9/+3Qeff/1F+Pd//9dvvnj7G//3nf8/WIrB0iRYrItgURfBEqRgGeAHoX7ws9eG+snnf/vk8z+No0QuUmujVrEhVf1hxBwj5mHE9C7gNGL67uzHEdO7UFPEFaDYD8/317/9OAf9ydd/+cOX33zzx6/+5akDbsWNagXmxsTV+YexS4xdJrEvTptWp03vEqXYrf7wtP/hk3/Ogf+m/9j4rN///Kv//Xf/9PXnX33zv778ehi3FFMRZZGKlZq3H4ZdY9h1GDavjpxXR87vgqawG0ChHx75h599eviTdtQi4qxCAuASDlxj5DqJHOd3Gb+LsogcW4rcw4G//+mvDoeNrZbGAE0EBEiYfhi3xbhtGLes7nBZ3eEyusMRIV7iH3w8yPW90JWLk6ABK7qxhRu9xdDbJPTFNy6rb1xGNzpyvuCG2b6+4K4/dZTmRYlbAwMVsHC9ewzfh+HX1bdeV996HX3rWMOL9tH7n7zqjru82QGwmLOCgaGzhlNHCHEbTOJ+ObxZ3ISLuGmQ8VYPXHKrxxxACjsDYGtNBMOHjhGt2RStzc8bV+eNo+ccww03xGobx40VQpwRqNkMqG2g0kFeh096CNQWcS5OFklKxdrcXZuDhu8YI06zMU57G9M04PnTNYbh4TsegrS9+xtLNVQlFWQ1bjHwCNJsDNLexjYNvK4Cz282ha/4tSDt51/+z2XURciZHZir1KYRmWLEaDbGaG8Dm0a9KkTAc343uPPu0oKs2py4KQvGOzuiMxujs7dhTWO2Rcw4eKrD3fXLT//b4RSHgggNDEnZANgNQ+QRn9kYn70Nbhp5W0WOg9vsh5H/7MOzt7ZooX6fMTqpNIhfdoRmNoZmbwObRu2rqHP5hbr3Vl192RqfqgjBbAzB3kYy5RRgFSbnMP1mBFa5VIVKXJVEarjAKAKwNgZgbwObRj0HYPhdHRaubbzzAhMo4tRAENHYm4SYI/hqM/CFK/CFK/CFGXzFp+rTz94/e9JFjZypkrE1kPAZU4RibcqZraAYrqAYDqDYT/lUUURjbYbGcIXGFkQCvovXaOwGShTC7UURfk0iPcwPEu2e7vX9hcVFWieKyKyChcAjAmszcnBRYdCqwqBhhRHSesgVPVdhcC0E7ghGjo1rjUkd8VcbY05alRi0KjFoWGKEK/s8RcRYqAF79QZARDUUzRThVxsDT1qVGLQqMWhUYsQX+niJQaDuJqAIVSAleIRfbQw6aVVi0KrEoFGJEe+wo70OFCoM3FpVa1YhPtARirUx4qRVhUGrCoNGFQbJA5fZzgNtUpo0x+ZNmsTvmhMUGwNQWlUXtKouaFRd0CYndJHeFCkhjujLx4iTVuUErcoJGpUTpHfiELdildxrVXWMrbuIvHyMN2lVWdCqsqBRZUGhbPzNz06/zRYuaI5wy8cQk1bFBK2KCRoWE+3eDG4xgyPW8hnWWtQPtKofaFQ/xO7z6zm+1Y1shauJsytBRbDwCnGEWT7twa5g1qJ6oFH1wAF0nK6ZuGgjAwM2I2gaqmOOUMtnUGtRP9CqfqBR/cABVf/9x6/9ci9SmgtLVVAgbY7mHOOOSMtnSAtXSAtXSGvQgGUORNdnx2h7YikqjOzWEJukk44oy2co6/kZA8woiwPk+OBXA/Znk9Tk2gwNoDIjtoi1OGItn2EtXGEtXGGt0ShNQB0//+Uvz6Z45aIG2NCgmhq2gLYkoi2foS1coS1coS3KaIsDDPnkV4NLfONCcynWTK0Rs4lJuMYlgi+EGfrCFfrCFfoazNJwwCIffvTaPF9821ZQqYmKdu5LYwElEX4hzPAXrvAXrfAXZfzFAZYMmd2tb7uCFSQEMSTpzcgQeIRjCDM8tuiu06q7Tu9SxmPst+Ix9oDHJOIxhBkgoxUgoxUgowzIBG4sKaS2Ag0rowoKOIV7WyIgQ5ghMlohMlohMsqITAIi+/h3x7lNlmIkItYQjLXGyCMoQ5ihMlqhMlqhssHQiARU9sE/vq5TszhsKMhIQuLYg/YWByAjHkOYATJaATJaATLKgEwCIPvkw9eWHFfkF1mpItQUpKqoho6rRFiGMMNltMJlNMdlb8cnQ+ABl/3mw9fCk8umqxSrJgStEQJrHCSRiMsQZsCMVsCM5sDs7WxoiLw+cKk9l+UVa2FBIwbX2uJ3XSMiQ5hBMlpBMppDMv6OEg8RbzNDl+80aR+CM0VuphTf6ZpAGc5AGc1B2ds8ngae32mxW99psfBO1wTEcAzEtiaaB+90SOnzw1GkBVhJ+iQzmCoGCFoTEsMxEuNVl4pXXarhLHdM7V+/cg7u6oRbwQbcHCpJRfcQdcJlOMZlvOpU8apTxaNOVczr4bzM00QZWXFrhCrG5umkEyzDMSzjVZOKV00qHjWpZJMDvXyuIglaEwrD6XrC/GXmVV+KR30p8d3b+oo4UCwo3i9qBaNIFNUExXC2nLBoTvGqOcWj5lSc1P6nj8+NtKqXZtjAvLfkDAKtXxMIwzEI41VniledKR51pur2kNDlw9ykQGWv1ITMNS7gJAyGYwzGq14Vr3pVPOpV1VBp/NcPf3Py2oai4FS1grB6H+oN2zcJiOEYiPGqYcWrhhWPGlY1VBu/+PS1oHuR5A1KrYYmfc/Maiw0NGEwGmMwXvWueNW74lHvqoZC41eHx/+gAGifXkavlft9RvG0EyqjGSpbtLN41c7iUTurPtJ33rrIY+dZEwqjGQpb75WtUNigiVU3J1lXJVWcYtWEuWiGuRYtq6vduYy56iO1xN5dHcsJTVCLZlBr0aXiVZdquCZY720314i0NCEtmiGtRW+KV70pHvWm6iM07rPXcY0kriZcRdOlzxWuWjSieNSI0kdmNTcuYI2TmprQFM3Q1KLzxKvOE486T4o337eKMdIEn2gGnxbNJl41m3jUbFK67b5VCjFawko0w0qL5hKvmks8ai4p333fKsdQE0TiGURatJN41U7iUTtJ5db7ViXGmQARzwDRop3Eq3YSj9pJGgDR6/uFK/irVkS4ufYJCPYAfy1BI55Bo0U3iVfdJB51k1QfiHnj9m0NivWJS0NEjQPFlsASz8DSopPEq04SjzpJarsnfZHTzaUgi5g1qhKXri0BJ54Bp0U3iVfdJB51k/SRhvhz97KDFTE3bZWdzAITaQlC8QxCLdpIvG4jUYZQ+shy156QBkFpVKE6VQaHwGBYQlU8Q1WLLhKvu0icUZVt6gpc5LezlK4kIe6qDhxIWEsQi2cQa9FJ4nUniTPEMrzxBnexvniuAtp3VCNpYwls8QxsLZtINAdbMuqUGt17g7tCaQreR/ekkkfZkIS/ZLrAeKcU1PkvW+C70T1CQeFmgYduCY1NAtcVYaUrwkqHU8iPoJTnLnFRK9AqmnhjqWlkryVgNg4ZYdFy6H+cnjXCiHrfH+S6KvnXc1wtgTOZDrA9P3w92PgK4Oz1K0DXekhS3CtU5EZsNQK0lgDaJHJfVZC+qiB9VF2R70Z+sbTKAspCLNhagOItoTOZ9oqfbqwNsjxOs70+5ss9CikKZoZcrUKEKi1htEnctrrJbXWT2+gmT2Ndr+yRX84GeCuNG1bvEM1qFE5pCaKN48aVhgiuNERwqKcRpyKO5jgTFGxsQv28W9zAbwmgybjwktXjJavHS4Yr+HZzjqNTFxEhqarKyBBf7YTSxoEjLgqR/sfVYQ/w+L5y5WWar+UrPeO0mT7QgjzCFXmEI1Il7oadXWN1L0RVuL9hvQgLdYhnjDYOuq7SvK7SvA4xWlzVPjv2QwRdCwqIGhAohwfMM0wbRo3wXabOYBpPo0YcjbOlXZrzOS5YHFWhauVmNc4LeAZqP4pk508JVzxDtHHMvspxX+W4D3N889m+zHEr2pTQoCkARA7NM0obEyuyQmmyQmkyrEUe+bT3kvzi684wbRg4rpRGcKU0gkPBjf2ve6kYdPFhZ4w2FWF4Xl5lEDTfjclZSgMURFZ3bnGc0TNQGweuq2dbV8+2jp7tuCZ3HJRXLSjqLkRdDDSyK55x2jDuThisqIZ5MYIwpJVuvcnNui5WNQPjqkzhsBEySJs2bJ8fgrrebD+f5mtw+rIQ+Ejgp2uwh77vnTS/+LxfFgJD4DPVu0VjZFWPwLAe+Ulh+ct64ENR+4pq8BXV4MOv+yfF5S8Lgj8Mu06Xf0/yiA9BtU3MskZrLxuCD4VeV3leV3leh3X3IyTLk4oG4gUYrQt3WsMoJf+yIfhIyN8/RLMnbP509z8OLvPtT/taRwkKm3Eja65Uo5b6y45gCH2m8DivQPsfV4vPo0Wj8I4N9St2KVTB6mQAJp7TPMG1SeC2SnNbpbmN0jzuiR4U7mCoxXpjBCsz1JYPO0G1OlUdet4e5PrTfv1hX9MNrTRlZ0XGWpNLBib1/Fnop3uAbe+4r7LcoKBXZNDaDz4+30k8fxL26T5gXH1//YkvJcSwVFKmio20cVIaT1L6WKeT3SfBeYRq5/O84zVw7BYZfZHQEjxPovqz0E/jNbo3z/vyO5MJKlR3o2QSkQHbjDQ/OtwQ+cSziQ5aCLCKQQNhia5HmDT1Z1FvmYIMbrXNR+wBqmWlQIVJV38SN660uHGlxY1DXeqozXPDQ6ZcoIkxSUPn/I5lvDbmkG8mU8/mOUERIhYWhgY5zTNWGwZ9N5F6Os0Fi1WubF6Vo0IkJpV9rFMlk+c1ia4JxRuSvNbiJtyPW0009rwxSe1PQr+bUzypqmdWGGql1n37IE6VY1LaxzrdHD45y7KPzS+z/AKaJ7X9WeSnifNNaP5I7b3C5klxfxL36Ufsp8XmSX0f65Q4f3pF74Ep1PN5jlwYsU/e1qoURcgwqe/PAm+roqStipL2SPf3eJpfQfMkwo91TCHL6vuW1fctT4PUp/P8CqImBf5Z1L66z311n/vwPn/k9d7RKL96ujNWG8aNK9SCK9SCY9SyXYhd3+cXL3jCazojzo86U+6zDhcNoiXhkKT4J1HjqvDGVeGN462Cn5hwSNr8OHERPyy3F2+180ovbFYcu5yPgmASwcCk0T+L/LA90r4R1jWLvHbDwqTajxM39dMOI494Bz1Zl1yYBmGS8Mepn/pRaVzaTvSrT1y5sGtroL3fH+ePMen448RM/bAG30PeKpsv2dJdBZOWP0791I8q/ER/lZNp3rQwgFcjq91ZOt1qCa/NndRPSofsm61cpfnScAWTmj9OnNQPr7PH/YIb3jHwQlCBuVXzmnylk5w/To3Un6dSR5f5IzZ/T3aACYpWg74J2bxpNDbEJOWPE/f0HfP4UZbfLUXITAU7UAURgEy2ZDX/qX36Bji/nte7Ic2lu5Z2hG6MUNVj5AmuTQzUtzYrBjsGj8C1Z23/agFkbAZE4JRsl7Oc/8RMfasvNoh52+PxKs1Vi2glqtxl0I1T5AmtTVzVdZXnuspzHeb5T16WZJX/ia26rq42XV1t+ogvzck8b15YnQGbV3SLW96Y9f0npuq6KkJ1VYTqSKwjNg2O53nf6G+ELIBNiTla8WCW+Z9Ebqs8t1We2zDPb1dAF6RCxmxNzDqFHiNPgG1iKm+r+9xW97kN7/NHANuTagbExagKqmlj4FSQZIX/iZ28re5zW93nNrzPtx2Zr/Kca0EzqV2WhrlZzPOs9D+xlG+rPG+rPG/DPN8GbNeuDlqUXJy5AufAM2AbI9WtdslA6f8RwPZkml/41GBW/Z9YzLdVmrdVmrdRmseO4Pk0Vy+VufbNim5XIynyBNgmRvO+SnNfpbkPx5BvN+WWBsVbVWh9wMU8FiZZ+X9iNr+1FDo480cA25N57lSETUUrSkXxdNoJqk0s2H2V577Kcx/m+TazdqlOw6U11yYNaq2A8fHOVgBjD/Y+cjufZILVJBM84utxgz782rEGsxnA2Iv9+3ni6UjPasdilOePALYnFaXXXjWYzQD+A4V8p0sPZjeAsf/81vzWoBaLdibvf/qrg6pyWJzVmyNpn8qN/d/sBTC2n9/bIhocd9sN+lJCsDRn8EpdJJNaJFKzIcDYhL5vfc4vNVxdaji81PyBwHf09Gpp4gQo5CKC8UrLdgBjG/qtVdgBgRz9Tc5muZUG3f6gNgStaVovOwOMTen3ptYG7g94d5Z7MUVBNiZtarEGzXYBY2/6rUGHkbZ8gKj/8Mk/H81yLgzchzMJ3UhTYyx7B4yt6nElR4QrOaL+x8GB8wNxPy26VVi1NauAJMhRqQWzkcDYuH5v4nzg9CG7QV/amQuDIGvr1vXQNNYj2VxgbF+PqxEHXI044HDEIXqcnE9zcXb2Vt2smadHLIG1sYE90upeo9W9RsN7TW9N81pNVIEdxCQVn9l2YOxej6uFUFwthOLQyz1aoNyQ5krgToSNUSnadGH2Ihib2O9NKQ5Ou92d5dq6HCy71SZJ4xqzMcHYwx5XU2u4mlrrf7w2SDmc5SYNROqLprmmoju7FPhsJHWhskbTHfcu9jxyS41+Ka897Mscb4i92V8ViRjTWUekRmMD++8jG4T9XWTLsAcmFLh71tdZ3l9uV+fKjkAckXlyK5iEDitkDitkDkNkHu1U7gjduXfEEEWrG8VufzIsIJiNpW7Ibw0cOQJa+/ij1xrHLj2/xYRUun6HGjCnhn9yLSCYKgGfnNWLhivDsHfsB6Wh9QZwJQYATMcd0RrBTB12Ebes4pZh3HX3uK/d+KQ5d79vBCe3NJeanAsIZrvPRyd6og/L6Uzv7LGDqNfq7GmCK5kXEMxa/kcHPKIRy/FM7xabZqDUsDmktndyLyCYtb2PNvyjE8sdmV4RHSpY04bNLBajyb+AYNz9PtwDjpYshzO9ogszuNQ+fl7j1ZYsDAjGne/DLcHox/L6qK9TndQV+6wiWMP0iScTA4IxXj3cJIqeLLekOot8x6AbWEvALbkYvCx93E8lR2uW195u60QXAjQUQmaraZMouRgQjonFw1yTBcj20S8G1slbLofcPe+7eTJX6E3/iNqSjwHhmFqkhUF4/+PUcul7tiZELruRXzoCSgFRqERkDDUpziUnA8IZvzh3EkZaOAl/T9mEyKMlzasjXzk+SnHEyi7oVZXSO5YQG86oxblvKdLCtxSH8mMWnfNGQW+4ItZiZkCqiI3y650AG86IxblHYv/j6qgHC7EWnfPOJ7kWFeqGNCDQ8mhLMjIgnLGLc0e1/sfVeY8c1aIJ0dEkt1KhAYC7srQ0kpuMDAhnzOJR1sWif97hJG+FrceLrVuMpXG95GRAOEZrq4cbVg83DB/uFs3Fzme5F+LmVrlBM0iL/snJgHA8qHiYcWnRQe9klnfpEhDpiqF90SAleYJpNPO3PUq3tOigdxqyGBTvUudu2t0xORYlycuAaEyvHeZbWsBqv/vZ66aYrqe3CoEwt16CE6W1kmRlQDRbqDlKtjR5IO6njdWx7xhQbd3vFvIabLIyIPpRdmla3Q36akyxz2c2NGu1+mDUIVkZEI2ptcNcS9PdwC/znAvUCm7Vq2hLk6nJzIBozK4dplqa7X3fqyznotYLUGbxinGKiZKTAdGYWDvMs7R2d5ZLodacDUyEOXINlJwMiGbzekdplua3Z7kUh9qqNmTHWnPoCa3Rj4PW/gOEnuAazWwcFvP2q/k1GM6vxQns4+lOVl7mcRuZqrc02UPJ0+BFYWMIVJ9X/x4NezwS+ZMLkr0d+nLchpUg6rVQ8jIgHsO1023BgFN/+eHpqkSKNedaK4P2XpHHyBNg4zFgOwxUI8H0+sivbvU+eF6tEjdttUU/c0qGBsRj0FZXWV5XWV5HWR4L0fNHrgXNG3aja2eMQlyUDA2IZ/vPtzYGh4E/CV0KWu+CNvPmpHFKk5KfAfGPsgQcp7ju+LylAau0ilSBw2gPJTcD4jFmOwxTY8vghq9b2aEfd/NmVVLgCbPxuBV6GqzibUmuhaqBYjcba2Bx052SmQHxeGTvMEz1298wKwhqrSopElKUiqXkZUA83a842Qx0vTnLrTvTmGlXk0RrUfmbkpnBiyTY/R1BhPvSvK+V9FUarWLKNR92gmoT//rDJUkc0vzwo09Oe3ZgUaxC2mGag0U2lZKbAU3s3A8D8/hyD0N/vmWAVNygM0zYG6Gu6WZLUG1ibX4YncdX7PVHvhJMldJXaYCkARIBR5yWzAxo4nR9Gpk/ctp7id5rb5XeE/RWJdKKlAwNaOJ/fJpE3v7ErzK9FmlG3NXttQq1WJQkPwOaWCAf1iaKhOprv/DLE+8d4Na3Qvuhc8r1ZGpAE0/cwwDdt0989YVbEWIUAGFvCrEXSsnQgCbesIfRuW/fa1d53goAOyJb67gt7n1TsjSgqVvoUXgeEdvxPG+lNtE+3cG1VZSI2JKrAU0dJM+C9CjTczTRvaBWqQLSuIlarMaSpQFNzSOPYjaE8H3/9h//y+m3rJjU1qc8TF8mVCNeTa4GNPVSPNr2R9yO/eorL07QBZHdRNk9jrhQsjagqb3eUdyG9EjoT+oDF3DpQ7luxCw1HXdCbROntcOoDaOA6PlUp0LqVbAvWQD54D1LuG3iOXYYt2HU4jqe6lS6rgMhu5oRa7zWk7kBTSy4tppFg8ijxMPrI1/munbpVOyuuIIN40gTJW8Dmjgybd1tWRMaYzF+R7KbMzWsroyYpjUpmRvQ1J5o424bhB7XDl57t11muqs1RXWFBkbxTk/OBjQ16dm43wZxx+LsaKZzQSERNK+tQtyQpWRtQD+OYwvG+uR8nncvKgPqwrGKfVI1hp6g28TEY6tbNJB934du1woXjgroXrkvkqViPLkb0MTEY6soHfqX3AZfuKgqNgKv2MXX0o2eINvExGOrJB3E/BBk210GFzAldHEyj1PolAwOaGLjsVWTDkLfR25XqpoFsLIQuaib1IReEm4b23jsFaWDyPdx20pdsmDryh7sIqqeOIhkcUBjI4+9rtEg6ocw2wYJIYVVKpC4EGvi2pLDAY2NPE6b5NI+aLvM88oOjaoLQG2pf5IcDmhi5LFFQwwtTG7Nc0NWJXU26xujKewE2SZeHodROu1DtutUb62RUB/1EbEolEzJ5YAmbh6HUTo9BNyeR+m19P13oubMKJgIt+RxQBMvj8MonSNq+/XPDnoMMkohdKemQC456gTYpm4eR2E6R8D2+qgvwQtJUWcnJeKXjdEYewJud/h5DGKPwO31sV869tSCak7chDETrMnngCZ+HodhOkfcNoz8SZgutaigE4oyCdUIVpPRAU1sLQ7jdI6Q7YZUr1oQq2MX92CJ0mSUnA5o4mtxGKdzxG3nM1211OaOXbtIOBrHUrI6oLG7xWmczhG5nb3VzQooOwoTV05WRZTcDmhsbXEaqHOEbTfkeuvusebdDpyV06xusjugsbnFaazOEbq99m67ynRvBbqYjVdl634mMfAE3CYOF4ehOkfg9tlvTqa6A8RAE1KbGFocBucSkdrrA70E55CjTQhtYmJxGI9LRGjDaJ/P5/7vx1ATIJt4VxyG4BIB2dEM7v96DDThr7HQ92kNxfgcf/T+6Tk1VSukUrsfDWja+6XkXkBjpW9YSQHDSgoYxlLAUZxlFPnzyWx9W8qhr1JUN4QIQ5J/AY2Fvk874EYUctS/Xqi7TPVGQEUkSQsFybuAxkLfdwsovj7oy2taqa/PtNY9OrBhGuNI9gU0Vvo+3daP8GsY+sad3f2OqU/VU2/xJoUWSg4GNFb67iOV889bV5+3jj7vuBp3NM8rcyHzpozsfeg6Bp2A11jp+/t5ymk1Pf+4bXSbp9nb4140jlpQGZSp0SjNExIbS30fX+nfNDO/sqsw7mOoVMXYPOmEUnIwoLHS92lfsTR6++oDX00kAkPRxiKK3hvc6TpP6Gwi9Q0r9wJYuRfAKM39dn8thGblpZo0lcaiKfSI13gi9314WyoNYx53VUOUWvpIIjkCV4pMYXIx4LHm9fl1qc1PfJXpBFREBQhqbd03MQSdHAx4oni9sqOBlR0NDO1o0vzpeXyOola8vRgeo0tyb6DkYsAT1euVewOs3Btg6N6A+AhC39skYSkGTZigNWnpWk9eBjxRvebVtc6ra51H13qavX1tcbLKdQUs8iKmp9WqROySjAx4InktK+wiK+wio0sdafu4rxdotBVUZHbqApJp0zs5GfBE9vr07G3sgpy/1aW1YirdjoelpsAjbOOJ6PXhlSl8yNv8yUSvogWoojp1RUGNJXiyMeCJ5vXhfak0aX0DflHgQt2fpcsxOUcZZEpWBjxWvT6N03HfG/Uq01W7CHSttY/DYZapSVYGPFa9Po3V05j5ax0UV0Pmzn3L3YlMuE+gxpgTaJuoXh9G6hhZttcbCV52f4AL+gvBCMiQ10GTlwFPdK9PQ/VItR03UeSXpW/1Ji/TWlFfj5KVAU91r89C9ci3HfXMZKJi1SpWwP6/aQY1eRnwWPn6tOhY2ir49W9fp2t/Sb60wtWRSSoqURrdSVYGPBa/hpWbIKzcBGHoJoiRbBsGvnWpAxaqBNIQ+8eeLrhkZcBj9evjW3Kpx/vq0JcMjBQUceW+MAUqKdUTbhvrXx9flIt82+vDvqZgrEBffXZh6iRMhDDJz4AnUtCna/JIuh0XF0S0QihWoQIqmqSLPaG3iSL06XXYyLz9/ccH+UaCws2oqZGyYdNILidLA57oQR/+yNMazTDsjYudoDgCsKk2ME57csnVgCeC0Ic/c4qc2+vP+2pTrnMRZN/J3FtN3eHkasATVejDFXlaHzqb6Vi8q0l6rShmnPjG5GvAE03ow/KCFDm3856KyEVrQ2pVyAyTTlHyNuCJKPThqjwtTx02EEUu3mGr95lErJgUY5O1AU+koQ+X5BSJt6N2sX3a3JkdmKt0bj2dd0JuY2Ho0yomaWPshlSXoohA2P1igRIJk/wNeCwMfVrHhCLr9sHHpx2hKxQQqqQijKCYkj2Bt7Ew9OmiPG3LDUN/ct68WhEHYu/3WotusZQcDngsCX26HKfIub3+uC9JmO5Gxea1b3FQ9dhISR4HPJGGPlySpzXB85luVLhVVRVqjfNzlqDbRBr6MFSnyLx9+tn7xxId+p3e58wRqKVVWE4mBzxRhT6N0yPjNox5k20srQ87AaNyN0CPoSfgNtGFPo3UI+X2+tAvycZuj0zdXo+kUpUYecJtE3no00g9sm4nE50KWEUHfumlxOqEk70BT5ShT8P0SLid7yAxihdGqAzQ51+iRTAngwOeiEOfxun7Q25XmU6gpRoYoTRvGukXTkYHPBaJPo7Ud6fclqmuXBqDI7lUEIwxJ8A2loc+DtP3R9wuU50JC3h3CBYAiliVk8kBTwSiT8P0/Tm3y61Q6y0FpK7YUxMNwcnlgMcy0adRetqAPpnowrWXZdKsX2+pIOXkc8BjgejTMJ0fGnDby3RxKs1QrZlWk/SIJ6sDnohEH+bU0/L3+VSvFQpyl2Ijgr4THENPyG2iFH0YqHOk3H726TEZeCrQELA2ZcFmkXLi5HbAE43ow0A97bsPY96UnkMUkK7CRhUaxvcs2R3wRCT6MFDnyLa9PvRL8TkU664etcu4tARak9/Bf57IE26bCGQfLlGSyMHRTxwbIGKr6i9wNX3jCbhN9LEP1yicSMZfnZ7n5FK56w3WSpW6nUsMPQO3MWY9XKIkfYfXh34pu1eb9XmTyn3rKtrYcLI94LFC9ukKhRPVOIr8adU97lJktQp4bXGjkpPhAU/0sQ9XKEnS4pNfnE70WkufYQV8UebqSlUh9mR5wGN97NMlCkeW8fWxX4k06ct+Yb/eVBA4+lxwcj3gsT728Rolko0f/+6Ycg2BQvGuLokVWlLd4+R5wGN97OMlSmQZhzHv4TZoXpQAmqA2S9xyMj3giTz24UX5pGPy+tAvRyGwld6r6b2jVt3ic5ZsD3iij314U54j2/ha3Yelbk2FGGZCaRM97MOb8Umu5byYR/+JGG2CZxMJ7NNoPHKJr4/2CqO0fLQJkE10r08D8IcEaZ7M4CRHw8m+gCdK14d33jkShjdksOdDTbhrIm59eNn9gPjOlbhB0t7h5FHAEznrw8BaIjl4MIP7vx3DTKBqomB9GEs/JjG0p9SRVIY42RDwWLT6NHqWSP2dz2DMR5sA1ESn+jBefkxS6ckMToJKnNwGeCJMfRgiS2S5bshgyoeaMNNYjvo0by+R2TqfwZyPNkGmiQL1YaZeIqN1MoM5n2kCSxPF6cPkvET26oYMlnyoCTNNRKYP42CJjNX5DJZ8tAkyTZSlD+NgiVTVyQyu6UyTOQBPpKQPU88SWakbMrimQ02WADwRjz7MNkskos5nsOajTZBpohd9GgdHBupkBms+0wSWJgrRp3FwZJtuyGDLh5ow01gU+jgOfohg2srgTDMldX+e6ECfxsEP0UxPZnDml5KcP090n0/j4H1+6TKDM8GUBPx5LPV8es5c9hWPL4UW89EmyDSRdz687i37NNMqhzPDlHT6eSLvfBgJ132xtcvOnpEWQEepFU0xzSwkoX6eiD0fxsV1fxrtqrNn7UVFk1ndyDw6DXFS6ueJ+PNhlFwfGkZ77oauTaAbLFVq3XBHUzsz6fRzm21+HuWOa+Sibsj11sVi3Q29tW5CEkNPYKtNNz9PEsk1MlPnU91rLVC9m7lzUjLgpNPP7UfZ/KyRqzqY6ApIhQkQ+icucSOMk2Q/tx9l7bPuS61dKp6DeqmtuyuRdDWD9I0nTNZ+lL3P+pDa2k6iK5J2h0hp1YBbFBfkpOfP7UdZ+6wPSa49menYpCCAmmF1yKedYNpY2v80Aq/7UmuXmU6ChRWaNkWhNJKVtP15ou1/mJaukec6n+jkrSghKMCLZ2CIPMn780Te/zBHXSP1dVQRWrnW0hpSxUpS0/Zj0vfnib7/aaAeKbDXft6XiS7Y3a1RhNzc4mo3J3V/nqj7n0bpkQ47n+hiUARQWYQlj6IlfX+e6PufBumRITub6JWsvHg81+YALSK2JPDPE4H/0yj9ocXPnUSvTYoTARr3Ld8WA0+wbaLvfxqj37712Rf4CzbqUtAAEj3cOUn880Ti/zRIf2jp8+lEV/ci0mUxqCaJXE4K/zxW+D+O0u/f+lTro8VdrAINwVq62CJsk4nC/2mQfvvWp7auRaRkjVGra7rcImr7TxN5kvmXibcBfHdzzyLHVeQ48Ce6cd9Vm2EhIjdRQuQIXZK8v4ytDb7/fz6NeSUNPDSiur88cWpF+lkrmHIiGJO8v4ydDU5Xo3r7tqt6q8WEuVrtSg7xXk8i/zI2NsBVnwRXfRIc9kn0IZbxuUQ3EC4AXF9EGzQtuyZxfxkbG5yuw3WfXrxKdEOA0kUzBUSwRXdnTvL+MvY1QFrda7S612h4rz1EMO4kumG1UomdsbkBptstojaZGBscbgjqQzTjk4lOKMWaIDFXQk/XWgRtMvE1OMw96D69eJnoZFSga8rJSCiVk7a/TGwNDq/I6L6lw6WfJHlhkApKSjVaK3JS+JeJq8Fh6kX3WcZVqnPTUlW0S+qZUSzKkra/jH0NThv06EME40YdbiJcGklrjpluSsL+MrY0OO+jeft9XgELtAoNlBpYrMqStr+MLQ1AVgcuqwOX4YE/xDA+nea1ttL5FiNoTGnpMQn7y8TR4DDJpvv04mWiK9aiUEW5chOK91oS9peJp0FdHXhdHXgdHvhD/OKGP7AalaZVq7izpg3+pOwvE0ODw7Ozui8tt0p0YyhItYmKNGvx/U6a/jLxMzjMq+r9zqlmzQo3BTYH9hrLk6TpL/ijuFHpzdap1kSKihL5i3lJrE2SqL9MbBxsdeS2OnIbHvmt3qnmgKX7nRM0FIb0gie4NnFwOMwm6/3eqebVC6oqEqlLtAjmJOkvExeHtjrwtjrwNnSEvt06tQFqEdIGbCSa2PSk6i8TG4fDbLrduDxqeXk0KfjLxLPhsMGa3b88anl5NMn2y9iq4TRbbrcvj1peHk1i/TI2Z+iU75w3hBVvCMOjvXF51PLyaBLml7EVw2li2O5fHrW8PJq0+GXswHCaDLbbl0ctL48mEf5FsPN2x2okCfE7H+TjwV4e7SDaBK4mDhNbnLcOot18cS4PNmdxRlTj0cIV9Ycr6m/Mcdv+uuzqckqbspLU9WVsI7GlgISDDN7flL1mveKxShLUl4lzxBaZPcjgh1ZlN6muFGxCTlOziA36epDDDy3MPvm8pk1ZSbL5coc/xOBM9zdlr+msfKgJM00sIbY46sGhPrQqu5XBaWFWkjS+TFwgtpjpwdHuL8wuaat8qgk0TawftojowanuirFd81T5UBNmmlg9bNHPg0PdV2S7JKfywSbINDF32CKcBwe7vzC7yuC0KytJ514mjg5bDPPgVPd3Za8pqHSsSdlexiYOe8zy4FgfWpbdQMJpXVaSkr2MXRv2mOR8sG1fkG2RwS2JsUmSr5exU8MedZzPtD3Ep21lcEu0miTFepl4M2xRxoNjfYhWez6DW+LUJEnUy8SLYYsiHhzsPqe2yuDEp0lSpJeJAcMWIzw404f4tL0MTrSaJCl6mTgPbBHDg2N9iFbbyODEqUmSnpex1cAeKzw42H2aaZXBiWGSpDQvY3uBPUZ4cKYPMUx7GZxIJkka8zJ2FNgjhgfHuk8yXeVwJpqSqLyMTQT2eOHB0T5END3HRrTMMCUBeRn7BpzmSNs+w3SZwZliStLxMnEKOEyTtn1NtqsMzkRTEouXsTcArD5XWH2uMP5cHyKanszgzDAlYXgZ2wHsDTkPznSfYbrM4EwxJX14mToAPL9UPujgtH2K6SqDM82U5OFlqvl/lP5uN2r+t8wwJWF4mWj+Hya+2/2a/y1TTEkfXiaa/4f573a75n/LNFOSh5eJ5v9h+rvt00yrHM4MU5KGl4nq/2Hqu+0yTJcZnCmmpA8vE83/w+y3367575lmSvLwMtH8P0x/+z7NtMhgzwxTkoaXier/Yerb7x/c8kwyJYV4Gav+n+a//SGS6Xk2wjPNlOThZaz5f5r89n2aaZXBmWFK0vAyVv0/TX37/YNbnkmmpBAvE9X/w/y33z645ZloSgLxMlH9P0x/+42q/54ZpiQNLxPV/8PUt9+v+u+ZYkoK8TJR/T/Mf/vtqv+eiaYkEC8T1f/D9LffqPrvmWFK0vAyVv0/TX37/ar/nimmpBAvY9X/0/y3367675loSgLxMlb9P01/+42q/54ZpiQNL2PV/9PEt9+v+u+ZYkoK8TJR/T/Mf/vtqv+eiaYkEC8T1f/D9LfvE02rHM4cUxKHl7Hu/2nq2x/imDbYCM8UU9KHlztU/weHervqv2eaKQnCy1z1/yQj7Leq/nvmmJL8u0xU/w9zwgj7JNNVEr/8Row34aaJ0v9hVhhhn2e6SOOXn4jhJuA0DfcoL3wi3AeON8ebsNPEzeAwPYywz65dHm9m15K+u0x8DA4zxAi3znC9/PMx1ASgJr4Fh/lhhPunuF5+I8abMNTEruAwTYywz7JdZnJm2ZJ+u0ycCg7zxAi3znK9/PMx1ASkxsYEp3lihPunuV5+I8SbVNplbEdwmi5GuH2e6+UnYrgJUY2dCE7zxQj7dNsykzPXlgTZZeI8cJgtRrh/quvlN2K8CU1N/AYO08YIt891vfxEDDeBqYnRwGHe+MXv4c5MzpxbUlyXibXAYdYY4f7prpffiPEmNDU2FDhNHyPcPt/18hMx3ASmxk4Cp/ljhH36bZnJmXvLiupj74DT7DHC/VNeL78R401oauwYcJpGRrh9zuvlJ0K4WTx97BVwmkdGuHXS6+Wfj6FGIFUnCvmHWWSEfRLuOpM7Ffc//h8=\", BinaryEncoding.Base64), Compression.Deflate))),",
                "    Typed = Table.TransformColumnTypes(Source, {{\"order_id\", Int64.Type}, {\"customer_id\", Int64.Type}, {\"order_date\", type date}, {\"shipping_date\", type date}, {\"delivery_date\", type date}, {\"total_amount\", type number}, {\"currency\", type text}, {\"order_status\", type text}, {\"payment_method\", type text}, {\"total_amount_usd\", type number}})",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "products",
        "description": "Order lines. No quantity-sold field. Allocated order value uses each line price / total line prices on its order.",
        "lineageTag": "7f5530e9-0365-4a60-b47f-cad77c372602",
        "columns": [
          {
            "name": "product_id",
            "dataType": "int64",
            "sourceColumn": "product_id",
            "summarizeBy": "none",
            "lineageTag": "710266eb-ab10-401a-aaf8-61a60b5a01e9",
            "isHidden": true
          },
          {
            "name": "order_id",
            "dataType": "int64",
            "sourceColumn": "order_id",
            "summarizeBy": "none",
            "lineageTag": "a4df6890-021d-4a06-868d-be08d88ed47a",
            "isHidden": true
          },
          {
            "name": "name",
            "dataType": "string",
            "sourceColumn": "name",
            "summarizeBy": "none",
            "lineageTag": "fe371ead-13a4-4cf8-b787-f882dcd8f3e2"
          },
          {
            "name": "price",
            "dataType": "double",
            "sourceColumn": "price",
            "summarizeBy": "sum",
            "lineageTag": "1b9ba58f-2192-41c6-b17e-ba498fccd3db",
            "isHidden": true
          },
          {
            "name": "brand",
            "dataType": "string",
            "sourceColumn": "brand",
            "summarizeBy": "none",
            "lineageTag": "c4f83297-36b7-4862-97a3-3d38242663ed"
          },
          {
            "name": "stock_quatity",
            "dataType": "int64",
            "sourceColumn": "stock_quatity",
            "summarizeBy": "none",
            "lineageTag": "1045d110-fda5-47e2-94f4-f4d223d1f673"
          },
          {
            "name": "currency",
            "dataType": "string",
            "sourceColumn": "currency",
            "summarizeBy": "none",
            "lineageTag": "bf97274b-963f-4578-92a5-83f1d4b56530"
          },
          {
            "name": "price_usd",
            "dataType": "double",
            "sourceColumn": "price_usd",
            "summarizeBy": "sum",
            "lineageTag": "44e09ffd-3f53-4da8-8a5d-41d90dfc27f9"
          },
          {
            "name": "allocation_weight",
            "dataType": "double",
            "sourceColumn": "allocation_weight",
            "summarizeBy": "sum",
            "lineageTag": "75b503db-2e38-41ff-8220-9065cb16ca0b",
            "isHidden": true
          },
          {
            "name": "allocated_order_value_usd",
            "dataType": "double",
            "sourceColumn": "allocated_order_value_usd",
            "summarizeBy": "sum",
            "lineageTag": "5ddc127e-cc46-4e1b-99ef-555fa182a28c"
          }
        ],
        "partitions": [
          {
            "name": "products",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRecords(Json.Document(Binary.Decompress(Binary.FromText(\"3Z3tjlzHkaZvpaDfdiI+MyL9T6RlaixRQ4jyx3ixMErsMllQq4tT3S2NvNj7mfuYG1tEtShXnszqU52sotg7wMCYAdlm9Dkn8s2IN574X//nk7fbzcXtq5u/ry8++R3+5pPN9mK1ffd/XC2/X33yu0/+vNpeL1+tFi/Xl98tfr9dXV9/8ptP3m7Xr1af/A5LKamU33zy7XZ5dfGvP/zJbz65vtm8+u7v/3m7vFnf/PTJ7xB+88mr2+12dfXqp09+98mfXv7+3U/5++31xd5PWl5ebl4tb9abq7//uFq/fnOz+7f8/P9dXfz97p/4w/Ly9ue/SQpJ/+9v6lhoPxb6JZZnt69erRdfrpY3b1bbxcur1fK71XYvHp+Es/vzbTCkVTBPP50EkwUSZ2ADzgCFhsJCTqLq5IqOpHkaIu+HyL+E+OXmdn29+PPt+uZmc7X4fHl18e3y9b8ipOkTq/5857nVoT7/61eT52ac1IQzAhub20ionoqRKjA7E2vhaayyH6v8EuuL7fJi+cvj/OPy1Xerm71QZRLq7o93QqQqxD+++I9JiJrcURypQCkGOhKjJMsimUUUlbz4NETdD1F/CfHz1fb7//nv68XLV8vtP/4V2zS0n/9YGxzX391nf/q6Dk6NkhaQTIosBjoQW8GcRApnIQEo0jy+vB9b/iW2r9bfrRafrreL58v/WhAQV4mlii/+aBuc1sE9+frLOjguCQkw50KZTDQPBIeuyRnARUCAhGkane1HZ5Nc8+zZ4snqcu+tZDkqxUgd2tOvJi+lUkImBTY1NmSTkdgyp0KCkaewGFuTR30/Nm/PhNur15fL6+vVXg7VY48Emnk1s1tCBBcVYifykQjFS8rE7mCQBaxJo2U/wnIgjbYnBU7f0Lk8Wgf77MmLSZLJgEkIVYBzdtaR50kAmKxwBgPDwrl5nvHP2DvkockzT9bb79ZXiyf7ZwbK9NA4mG7o/keKhuYJRIuLoujQF0kAkrgwALq7CDZfJNZSBicHxl82m8vF081y76vE6Vt74KzwGRWjoyoGFZooKhGDVOfNP262F8urBS6+Xt1sN9UBf0Tm5BkFs1Mf4obMxC6YR848JEmK6qWU7AVy8+1hpWGQJ7lzpzhfvllv9x6UHanQ4H7ZIjmR5/hInJhNbOTcQ0xqmDNlQc7G3gZYCReUA+nlL8vLy33lkh+WWybHYCNgJIlkywWIMgMCj8SahApzAWYV9dxqNKwUDLYS5p1Oe3a5+WH/wOCjk4ven11EPYEBWMnAiE5DySUnjAxciD2zYJtCKzWDuTkU38VZn/tTxXbwWJwoti++/ksdZVwtCkuJQNXZhEe+TdgdrWBImQ2Ai2ETaCVs0CZZ9OXt6mK1eLLZ3Owfi9P0c0hz14/y088m+YeVU7GiZkUErQxJ7vjGSymMhbI4tF9npW7QW2H6c5KVw/Ktn15l5rb77qcMKLb2mKgUDJZJEv1mc7OaHOdwXA6d3ItaySLZUsmemYncII/kFVJOmkGJNZOINmmFKsVCcCCFPt9cbV5vl99PL0oPvO7OXZcQRRMWYjPISjyUYgSSFHIQRDQuLk3MlX4hPJhKXy6vLpaXe9+fybG5tA706z89qQP1VKBkzVSE1AuPnI+UslFhUorKAEjzAVJdpqH2fvHj+vvFN9vbq++uDyucwxeMmfOChZNKySUuiJZ1qEwze15QJXKID1QvphrgyOLFXKaR4bIaNJmGKjVDMpVrl+uL/XOdjrvp6swnR77L4xo5wtSLDd0ZFFMR8ahQkJmCNcFV8oW0Pgx+v13/9g/rm8XXt1dX66vXi5dvNtv9cy8fcyogzNQrkFMuYJ6LKhYbugOyJoJSEIwKOqu2L2QlYCgfyKi1fMnysDyq95cvSk6Obs5G7ow2cnQwJnLgosUBiEibeyBVCoasrarFDeOb9erwS3swgc6JbkzqDgWKqrJzHqrPJIJciglkBBXovLWVhKG2QvPl5vVm8c1vr+tb1LR4cTCFZrj/nohCiUo2A3GRnGWoxCaUGNhds7kptOdhJXGoTFLoVz9dxvu6fPXd2+Wr7/ainN4sjhOj7aGfgRMZFwiVkwWHajMmycULenFxaT9LroQOQ6tG/7DZvlotsFLbR6Qdn2u90HjnpQmiUi6MB3LL0SX7h1XVemcHpVIcCYxAMQ/JmGLJlEpRzblg24ipVAwf6jZNb0rTb/C4SsbLT6ciBuPHGP/yPyNfoDWpk+v2Eh+8G+lD70Z6rrsRefs6VoqFpUmPT98s11eLr1fLV/Ff1KnzHt/gnGmUqSVXM5ZMHNly7ECwxGpSuOR4ncGaA4ErGcPaK33O9JIOZEmeuTFoKlyMo6Dg7O4jnxqn7GRgwGYEnpvbIFfahfPBm9H9xZeDp/pETv/bV9N2WSIyiceXd02hkboEJxbNkIGyF7TCbZSVbmGbu/PGHf+eGsxMEp1ckz790+SDLCSJReK6axnHHiyxpCyMXMwRXTpPtlIy7Aey6Jeb5T+qD3SsIPz0y0kxA1I0+KhIJhAeKzhBYnVDA1CO+mMrZLgSMlzarLprhRo8tBNq9TP8/RdfTJIqpJwNBZ1yNh0qGSqnbICO0QLPht5IGKkkjEB7nw+9/eRyc3u9976ONgxffDn1IqilYvFhGqMr8EjHsEgyt2w/9wWkybBSSRyZNpd6LdEjdej0Jvxs8o5aMmEhIcjuRDhy0CfM5JKj30+W2wuFVGJG6OxV/KasqMzJipMzZXSgET2jYAkJQQxJovXUhFnJGzlkn3n/vi/PiW8cLdBwaeSO1D6ZaYHml/Pi883mYv/SOxU5B3Ioz92TTlAc3fVwHJUx7llQqMmhUikc0TaH/m2z+X7xYvV6eX27/+T0mERa6uf11d+mhyEmLQJalKSYlJEUE4ehkYiYIxhnbWOsZI60Paa2cHH0lX6SZZ7+e3MSQiYpTKVE2SL+c6y/xEhCUjCiLN56uiqRI9P20mnroi8+m54V4olBWJigEGoZkuNkSUWikyyaJeemhyaVqhFv0ul7+i3qL/LlZ19MT0TS5AQohQhJcKTOJpJMTQjcCcOd0mbTStbIIRfNL9q8qdR8lPd+RU0saMTRCfH2K9VK7ihM0u2//7DaXq//ubo4yiZ1nNX0LCYppRyuIcvIbpna01IryaNYp9z3c6LMlQNo9HwUa85HrcSNtv2mXbV0ejpObxjHdu7PYzqhnIAzSfgswXLGRsJppW102nC6q5Y+X11fr65e777G1/fImwPpdeqvaerCpCl7LiQgKGg4IlbFEzqwF1ASxVKaSCu9o9Jk16fL6zffr7araclj+kgP5tc5nwKhJWdSLihExoM+qbi3OGEWYyudJ1qbg3Uuv1a1j2mimUmtcw3FYYebtOU5rWSO5gN3/mGf/lxrESHuxYalCKr42K1fMyaUEpkzg1Fb2dBK6Kidq7D/zVfT3q8kzEwW5uciMuTtxlySGzpYiQaNQVMp1kriaNuCerLcbv7zdrV4sV1f3bS9qKONUXNP8xRWdnVJoFyUXMhKbm36ldTRaSvqULH/SNU6Oe3//NnLaVMxlJh6yYUQMueR4x5ShkKaFYRzCQNj49evhE1uXcJ3zszBkYRJhvn864loNU2lqKOQZkIbaik6JFVDkxgrMW2Fea4kTT7UqPrlyvyeFs2JNPhyWvSABBAnQBiC0IV1rPkfPyaHRROLKkc2ovbhViIoT9tVTze7wJ8u3x5WcgfSbT6XlNO20ZgrkZMn/akvV0+2m6sF+uHG/phxj0abU9oa93KlXnLbnPr0h/XyZrPtXh9Gs+bpDELa6utc6ZQ8bT4dvv81c4THyc4TThFqq05yPbZ0uNc07sKbqw7a8OvWFgdzJUPyoabSN9vlD6vL+lbAD+wozQ178nAmyK0rLVf6I08bR8+eLZ4vt99vrm4GB7F0JpbRR5SxDaUSF3nSHnrnQZuaJo66Zk+9Z00cw0+EmjCskg/WtoHuuu5PtstXq+pQPdrZebaiQeY2mkop2NktLTPvGw0n7CxtbJUWsKkW+DQqzc3layp9jqtcNX2ewpJQDSBmU9CHQvJsSYS95Ggsc2lknlUywTo2lmi4FnuoTuCZ4Jg5RVBEqpLBy5CIdUgWjjFDxNzaG60SENYKiOeri9vr5emuXE2YOVsiRSzAu0GLkfuzF0nIImZOKu3IolWiwqai4uXyH/9YL682BxsGR0720UyoDpAMBIopO2QY6i2DJbFoUSsXMmsKWlZJDmslx+eTQ+z4Qtbc/Clki3thQXQUxpGvsRAkJwUtpAwFmsuz1aPShyTIF6vV2+VlaJCri83t5fp//nu7eo+EOhN5WOYSQ2Fm3JUORiKPXGbAUmKWALip4FklUuwekfLyzeb28qKpyx7ZosWZvEQ5lwQSL6EY+lD9oIjFWGcWyDFA1pYPrJIxNpUxt1ffLb7c/FhVR465ms2FBpAwZ0CVKKQWH7lAlwzJM5RwKolSaQfiK23jrbZ5sbxc/vOfm8Vn379dbyeTVw1843DivT9WAQjsBnt2V0Yd8qEJ3BmWCAWF3ZrCpVfKx6dOl3cJ9/er7bc/xXu7uqdCe1zBq01LBBj9aEePjruMvK8xpgauGN16Fu34lrySQd6aXu7a7T+uLy9/OtxxP/aW1/sokxeS7MVVRUZe3FnHi1dKyA8CYzbb9T83V4vPltu3bzZXq3ussA9rJDSjAxbj00iMHPX3oUyELlEqBEX2GA5qJZJXEsmnjpjPvv92u1lfrLari5+tsT+uljer7YOtMVN74RmCjUkzFsgsxILujdb1Sih5xxjz5+Xbzfb75X891F04tYycZQqEXFIGM8OofkKrHrwSR96aYupGw5PL5T/3n+Qwq6oXLidgNEEtTEMzoMWTswcvgjTG2trvtdJKPrXHPF2+WU9FwtHAoxn4A5p5shJ8DisARUdeVyZIGOPpFI/U2yFXr9kyrTXm6ebq+mZ59WpyiNrRjYaZMHUn/Ny1mGkMH41koEJhvyDRnDMjQ3uIVmLID3ljDs0vTwX+w7zcbcy5JILobSmBoQ3huubIZKXSSKXxxbx9s75YL3uT6UeauWc/UIqbM5mrFhTJQ33dSI1EKhwnTNxqGlFfKn1UsN+DKA91xHwQNgsRBLwEiBwIMjenSak0UWm9Ms+2q1fL95mYmXtXT3FmCqYSlwLNym7a9nNLJYtK3yzzHqOFM29qKTkQZeHf0hyUnHMIg1KJoNLaZJ4ttxerq8WL5fbmp5nK/7EFhvatZfHoTpbiCgplLPWQha2I0MAzALTVolKJoHLIKvPy7Wp18dOC4Z5HOpdqP8Sjnf1KK01Upg6ab1ZXV+vrBRazzpc6PUgP2b5nAmXVmI/UUgBIy9BcwhEfaqWHysRF8/LJXV3h8/XrN9V58vCeb+80SZAzOxbMuwNl0PPtgILIuRT21uRVKj1UOrC9Dg5rdDzxLMlWc0LJpQgRBmKh0UKlhu015pnurPqRmXb21NxdLyBrDk8U5rExNrNAt6gZGGt4q1rA3oSw15pnDreNjx6hmXljP4jKQ6gpe3CoM/Zi8+rN6uZmtfj01avV9fVmvb2vUPSw9th50Luz3ypCzeaDXudsv7jQJt+pR2AQNRzTUpnj/oFBdoOR5DuvdHfMuP14O420z2+X2+WrN/sjKUfVdWcRE5CTEVgpkKNJNIYYnjtIEWpUHxzsph3d6B2vL5zi/j0vlRBqYh8c8usc2ZIYlMCnqKZI2f2E6EGaY4voRaihfdB21p5uLi+jonIR9oT1qmdPOHoqZ04xneKwNUhsxk7mJZO2YFuEmt8Hs2PkJ5/LaUbJ0cySFhJmLp5t7GRySfGuUBAQpfRe7BrsB9N2235mfrG53ExV1ZGzOTwzOC+UU8ZsDogMecgDwKApWnWEygzqvedcAwBh0m+Laci/3pV+/7HfvjjO6KDzTzTEvwsXR0UYap+SePLMhTMyqnYI4jgBF2PbePs5PX+23G7XV6/vmUw+1u3QxLp78cA97imFaSxUg4RF433QeKrtUTuFFzdtt2NmlI4zOTQRavbkJDuef3a0ocwUI7KUmTRgA84dUuyEbIxtw+2zH1aXP12tTlSMaJ8kS04xSe+2Q/cOuTlCNkHBQIzHgJJ1JPIEcIyHum5frX5Ybf9xe3m5eP78nqmBh2nj9luFnJMq5WgYl8J5qE0TM69MJphBSzHq0LdrKYXTrtuzZyGe/vN2ub2YGyI4riTRRBolCUWymGBGLCpDlz3IicJOYOAxKdzubMAJ8xg7Pbfwl724rAbRj6pKzCbeGBpzAM0WsECn82BZcII77vCOJ/M926B7jBWEZ0IO2QQcfCAk0JyHCk2ZE7gYkzgW7p00tWxquMfvVPHTN6vL69VyOupzrJN95ls9SawESYg4ptzBoff+1kIJ2ybcF6vLy0lNuAxOp/dihMQF414X/NQhMSgxE8XKVjRzyzHDCR4ZDzXgvr69Wnz64/KnIzoaDysMn+fRqqZiwvFks0lu26tYg5ORpm24lz9d/rD+F638+fpq3WIIBrpxZzp2zBKDauBCYyC/vcDX0GSkSTvui5+269XCqvvrw4vDbXBhfQAIFxaoGsNQcPP6lybLINp+3M/69/PV8mLx1erVd5d3OfaAQBwWwSeRiLMiuIYmY0NNbly/9/PejoOEnElGzOvhGqyM1Blkb6oTVbwN8u3Y0vF5YG/IiRHDQKmaqUX4YA1bRjrUpvt0++rNZfxX9khMU4z9e2LuzOmO5O0ecB4YKkTNi+Oavow0bdm9c0c0i6OOzMZzD/g07/S8bqzZy0idsfd34JCH5uQ59X+anHzECVurpw59+Wx40fOIivkzthZTDYm5Tcvb9eofr5bX9/n3j6sbn6eWeMQdvuYyI7cNvX/fLq/ep5s382hPcuLOJ6Ya3YwH2c3vHMKqi5e365v64fIDtfL8Rh9IgYDJEibJoe4Wm6WCAebIINgZiMca4IwNwfnrNz/1YYBj7NEmytifiIoZMTag0NAqv/mlIsiTbVuTHt6dX3bxfH2xsH2ZjAOetZa0wpYEOQr2KjgI/J9f4oA18Bk7xOdnm8uLd1r56/XV68MH7K8KIok6BZfsDjk60K2vFGvSMzao569Xv/3ZvXYbjcrF58uHmypkJtKTbNyaA+NjDX3GDvX56fLtavF0c7H4y/Lm1Z4BaLhi3O6KMSspPlGP2RtmGetcxaQZFDUKx3FnGyXW6Gc8yH7+9PL75eLJk73v9IGcp9mlB86UOHY8RUriMUv/DDkfa+gzNtTnP1xutsvLo3Azg/y8U3yrDGG32a0vViuKnbO11k098PM+tHTBXj3Yh5eLe48zESFmyOiBhBr19Gc1iJExL57bjU5YI6Cxw4Cuy8Wjfra5M/UULFpmShjqEEQAemWKmgWNDQw6WuuX65s3DQ/qyH7dLOcSMiaOmTFg8XgFR8KMNVg5NLDFhSk3U8lYQ6GxQ4X+9Ifl7qi5XF5Vphic2ruOrBW3kaJpclMnJnWBIdBl3H0BGd2A7rCvbai1SDpIhv798vuox0yS0gNz8Ny2uVPAPTnnFOUc0rCbkHEn5smW0k6/7uXt2+3q+1XPCX8kHGruVUZx31XySa1kch8Kdlbr1/RonOKjh8FRcwL4JFvM2Mtu+SfENCwWaydZsSZHYwcd/ef19ub2+lhT17EmtjZgKtHcCZwsZjfVIfQwBFEAWQA9E3O7UQFrjDQ2HOk7DXwg2rGBue5a62RFqGDGsIyOPFxBiiVTbC4W53Or+GuYNHZo0p+vbrerxedTGSzTvDSahZVi5SdlzDHaV3BELYXdzyiG9HerGrgj+GueNB4ESr9Y3axvVovnQfzYS8IPnJmbIyxnoYA7mGbLtDv8Hh4za0Iz0YBjMLu173ENk8aGJv3s2d2E8pPV8mq9OnyTG9TBp7jJieQUC0MLswL3Yqzl0hQk/R4o1Fn5u+uwKUjgMzHnA9x+CPinFKFsIgExkb3acb/skhTEWEsWhBYXgTVyej/kI8kfdKLzlTJzKmqs4jsy+oFfQJEcDnAmVasmJ/vvdWAocvTezWJhQBt/raf2mNtHOaAeKKhmbwUnuNRKLkmZNfJ8LHGQznteC6oGwT3LLJoito5bydWE64ApMxI5B8he++VTSK4c24EyZWQj4plzKgCymDEA5GjcCV8Phf/RFBohJpWYyTkgKrTfPOiuzYHEzsU9tnVBbjd2YY2yxg6LvOOk8UEnTRdknZNTFJe8sGD/xYYUK2GzU6yOR9mfFunvYqFEXMBUcAdib6O2Q1H3XAmto/5oV8KcAjuuhA6xWibvBgVIPL7gGfWZsLiGTYkCwYadV72WZHto9nsJekOzP03QJpLYYiWHW7xKA8lMgZN7yR7VA1XAzptdizE9tC/49CO151nEOrvWA/NEinVa11Nq4NCkaa+ck5DihkgALHzgkH7PbR6YJzLMD3YO2tv+kSfT7G2/SE7OoTSELZchvXlEpBP1VZqsfAd1mtZxjm4bTHRns9FbPWWPA1iExC0PzQ4XTIVz8YKUw5Dc9uVrGjbmuapra9JtFn8ce/FvQt5tt+KgmYO7gA5dmAonLwxFKbCQ5G1JvaZnY54K6wj01epm8+PV+M5IvT9S1JzEs3IG4h1vfSRSTS4lVjRREZHOGVNTtXGP2H6m5kETaGxaL7ECiqPoVIaK6cWSQ/yO1BGydiyONW8b8xyi7CQGhLm3OVxhsToDdjVYG+NilmQZBdmYsmdrb4k1mxv3WPBn99W0i+s1uaM4UoFSYtfnSKUyFrqHnZWwGOVOo7PGduMeLP50TV29P1KCVHLAxmKAuvAQXJDTzjJoCrv1ai18BWuoN+a2IvtusDgGu9rxtaNtCTTzYDmhZRIVNlItZWgpGidhiJkpj/3T4LltitX4b9wjzZ+ynTDzbD2ROnMxc1MaOoM4xaJtLjtAmFtpz6AaDY577PlTexzbrzSRgWQALVgkOGtDEe6KPBm4gJiUzrOsBVQ+VIl9fzvCXLwBdxWkAM868hiSLmWCEpsQPVC/7SojrHHhuIeuP1szoYm0pDBgZuYINyuNpd/sQTrlYurSITFjzQ7HPaz9uVq67SOlFDgojJKrm9jQumZOJg4iuoNq5879teaHo7WTE+fpiPXiNdC4eFJsJLIylpQcg5ofP4GIsfNkaxl1iHlfLxnPA9fXTk4CK+6ohBwm+gNVqNkATaHkwrFUD6hTX6wx4mjTfvV7W+hnXtwTHaQlKo+MKFmLUeu6qJnhaIeGJM7RBfvq2XR3ZegciqYdKWQY4upAEhPKsd02Zq6ZO/6Lmh2Oewj8szhqmjh3dhrg8ErHDnkcOlchiaNFn16jJAvYPtyaI457LPwz9XKbSDlJJt9tIyhSbMiQEIEGCQEYg7VkHUduDRFHm9sPeCLAWRMuhBPRYnW3kyPggWbIbLxRKw2/YFEtXDoOuBomjnv4+zN5GjuhssU0IWVFDjQMjL3EsSAw7HM7+jp0DAk1Uxz3aPgnNdN0AgzMZSHPruqseXBZ3m5ziYJ5dnSz9u5W48PRD81EnMMN1ok6WtcWmE/LRHlIL0XQRZihiIaVXjupqRZMezj8SQpu6mrN5W0wCUOsw80sGnX6WIw4+Hgpl4xh3wRz7H2qtVTag+KfZ7SnE2gG2u2CRiDMPLSFHpKyyF112MC8o5hqmDh626c726TauRKxCgEaCiGzaWeeqeaLo09bcyee6nn2+WRXazAYY3IjGrLZfIhukDk2YMeqVlYIq0ErmGq+OO5h8Wvs//N97D8d1Wufbn+aRohBXSse7VZSsSG5nyVFGUMptmeDdtBtNU0c/dBExLv+o57MPtIGzJ7EDHYhh49mJANnSQVRuQgWzZnaU6fmiqMf7M+dtBDRRkslOVF8YHFmwJDbL2syM6AcozPUOWJrzjj64RZdRzAdXQmWmSdLGqVgUyDfgbRpxK2ac8oScyQOAqGs22BrwVQOUswOUBxGk3ATr+ekYq5hf/GSh4bdsyUFB4BSMot3zMg1eBzLtEd3SndEE6LmRKqB+4RiWYd66dkTW8SGHluhOpbGmjeOpdOcO42lsf08MZGCZAckLGWs2nJ3SN3ttAtPRavxa8I4ltmuHJy+K9fEHvi2XUpCQcOxZXzBIAGJwS+LyYjO21uLpjJtyv3skVhd3jR8pJGFg+f4RC06XCWu9zk2DnIr9mvqOJa2DXfnW5s6FJtVZkeWIf72aWPJ1AQWVttCUnAIkqmYCITZ47pK1BlxqcnjWOYoZi/fbLb75aWpkDi2CdeEy5YARcNfXGI8bczBFEMRpB5bQaEzMUsTCHm5rwVXVUiPJJ9+kCgpSbC3d1tcel1zmgDIy6T9dqJFg01wJcUslcWcUXSNbUQWKSfQ2IKhRWPvW3Ow0IQwXg513t4ty9Q93UsPrP3izONEo2ScS+BdNZoXI/lWOWWLOxuzFO2YKamGjBNMu2+NC+LF5na/NDoGQW2ilZJYqWQidudMQ9UHlUTuhQ1MglDSiVbqaDvDEDuXIVT3mZO8v247nzBiiaGWg1bZDGgQF5UcyFu5N15JFi43ADENSnFzj6OaNk4H1wX8axLg2f4kwNR4+LDx9vaVBolGk3E09okP4Z7CMc3FqcQdldH5fm+87naeQYw2ZY6ZiPa3kOvfwpQ1speZh3cG8NwLnlPMl2VWQaHYcjr2ghdQ33XjC6r23nCrY52OQXR32I0ZTNvnG8zBbIZkAqJsY0CktDOXOlmMDHXMLlSjxgla3/+T9fa79VXti26ayqPqyWLdBTAYiLoP7TmLsSDePUlDja0hbYyljlFnxNM3v305uG98cqf74rOp7k/RMoVMIuYWGz9HBnhiqTprGDZz9HEaUUw1bJygU1PbOS5f3mxvX91Em464cr0//HrXhIoxq8AFkIHQA+kz8pGGP1pNKTYFq7d7qammjRNMleLv15urn64PuiMa0+Fx02lttCWIgTHXj5IxD5leckIrO2+QFcaW5EU1dpz21gJ8OINp+0pD8uKx3KRgcStDYJmYLo1+pFvxQrl1IRJOtNWU3HaCps7Mt4uQQAixOJNhfIFD3644cBZXJO1MJFHNHidsaW1PL9evFp93hpGmdadjuzpNpJqAop9DhTRsIkNobk05Rq9KvBxuKp1Qa0G1tyjg7E2dJmRLtttfbRzszKFKVCI1yBjLtTzOszbeWjphp9T2s9tSHtrp4Ll3N8W0p+0wgYhMQ4V/SwjZXGPMMl6OptZGNXqc9tYFzFzbx9ig5zleY/5SzXKQJNG8RXJTTR2nvf0A/avtk+XVxeY2+LerhcLJrrlN+IQxvk4WbhYokIfmOWLMIaY5sopl1t5TruUUTsFth6lt0+rMkWPBzyb75hFTDmfSDo8qakPDV3c/RCiHgipgbQGVagI5Yctt+9lj+s2b7ebHjtN0dDx2GjB7MjQvyiVjGfQTIKWYhtDiGO3KktsMVSPIaW91QK+9U9MHh0dhm6erSdxACOJ/Cw95Y1BSzG4ASbQXCLhVUzWRnHBSfXuvKe/poOQ0RkpM5AVN3JQJhm6wGDfYLNGyK67SKTDWFHLCqZVrD94wN8F/5Ihv8zDDoo8YqVjcDlZrZgLdvRExohZwh1h600Zay6a9ZQFnH/Jtnm2ckyEmDKJ3B2MhRyvWY3YwHi/3Xt9aPdEU3fb16refXax3uokA9JdN0K+rd3mk4NhGzClOXS0OqJxlbF25pZjPiwpc4JCh7VVSjR4najFu72l3mj14TpKaYo00l/goPNRUO/ZLNXuc9rYHvMvDXy5/ScXLq4tvBw3/H+TY8aQuObwTrK4orZ6qOeS0tz7g/WyYc1lYknOQX5TJXXRoLBSDqqqiAuLskq2959TQcaKpkeug3f/YZlb9GP/6739oKjFikuPbyoGCH2pRYrKAWcdEZd5ZL1tdWIPGiQ6BFs7h92+DhiARZHImD9jX0IK0VAh2Frj49cXi9zbmWjHRlN42s+djrOPTecJccvDlZNe11LGtFwmKhN+0WPwk7TzgWjFRy2879chrE6lGQTtaxyzsBDjEkk+UiwqG3x+o9E6aGjVOe3sCDrTb7/fBH1svbsKF5BbbDMKPxUZFhwDVKebyCbkE5Io7ra2aOk4MB1p5DweGzMbHKETZCNUUBMdWXaQcSFSMXaqCQchpI6zVEt9DW3h5uX779gSG2nN9pVaYHLVkRuwYEqmmjRMfIpbdb3h6v9JEE3tOOXqUmZmJCpWhblYq2TwAlRkcjDrZuNZNPG3Y3WngSdd9bOFd5+lalCJi6i9mV/PQhgBOKCSCVtQV2uFIqoHjxIcwXaeyO3USMIWhS5UVjPNQhS22K1l0hYpmDO9lG2Ytmbjt2O0XIlrmwPT2eqzdqfNUicKaRQIxtDI0iBRz+JgBS1GOOaTO9bWmjhN3GnancWF2MjBRLnf4vAKMg0PMOQeWHYpiEKna/FuDxomnbbpTOmk7DzHQ+MpYQAqKDd3IOblAAFSLlCjcdh5iLY/4UHuuVxaWfffTQ60iM49YkiFnUWK1rDQ0ti0prvZCYSQpAZ9so68lE8+vVmq3tY+NX3UCjn8siQfaxMSGVoRJClAAEReRnEvnll5jx0naVt2pEQRNpHeZFCQYZEGDs7FnG28HUHBjOXdKTTVznKRt1P1MIKirS8dXhGee592pGIuyLDrsQEPY06TB3SMtAqDeKffX6HGSSX+uY8c8yigxr4FJ5J1JzUjLULv17iPPkcvNYnCwE1+tjqTTnXtXDX4aq62f1nimoc3WnWh3eEDyuH85ex7Cqid3J6Ewh4hYu6CRatQ4yaEW3am5L028d3o9B1qJIZqmY/aIGGKOjgFzTAy0urAmjpP0e3LvN2810UrPP50utNOofHsJIYGGQ6gxRkm7aRAPRoN0Iq054yRtU+7E4IEmTnGMHqkH31JMbWjolUlSLlwobLq7CcI20lozSduNq4sQL5ZX9y3yPrYM3D5XCCCiF/K7XtoQFSUA8tkKcfzaetXDGjRO0mFRnQb70sYXLW8x8d0eGoUhtz+LpixYwv/FJKStPqxR4iSdbtzJuWJtsJwT5tgdkzMq6lA+Ys0JMchdEGTuFs9ENUGcdK4fd7qh1zbimPNzKigaRsSxMdDYQqNeCgb3RbhdLUo1NJx02o+bZaYfWwueecDOyQrECoMcbcih0bJYQwOZCwpTrKZvB5Ko5oWTnrsXd544PbaKWgwSSNjJW+lbA8JJfw2mZ3sAoaei7hrWcMxDbTkuniDwIUUzW6z0aGOvNZR21iqdZfXDn15O4v3l5wxECdDGVWslnWqlM203aMLKo1EJdKKqod+knRLS4PmpM3G8+ykPjwN7cdSqR1uw1CkHEtpgfvlJDw+HeuHUskZbfNR5Ngw8ezL1LkC2lKEUREfhIXWesyXKorE8BHJvcLMGeZNONc5JJ+anIXq2oLuG4SjWiA9t7LIYJykxXUZaDKE96GtwN+UPZzVqNmuXokkkSEMY3IexugjF0qMoTOtu+USr5Wp+N+WzbT1q46MkEVhMRFAAOEbiy7H9St0Dso+OnSZ+De6mPAVGnX6fQLsMnsCTZVArHBtOhkpAsa2WwrFM0RvsAC2o5nRTboFRp+7gN5FSsA+inOcWGGYbEm7KsUejeOYYMdLOCFSN56bcEqPOtlGgt9NHUtiVhdw1mi0DIe82xORY3kPBneo93FrX5KnP6PQbBc6yCb4YhxMwiEzRhW6xZ1QDuikfGm/7yLcRx9KjlJ1FMpao47eptwZ0Uz7EjjonvKS3ag9SrFPKEqtA95YwPSR2t7S7dFkWZ8md2GvllKcUqTPuFOhtP6W02zoHRqA4RMzdrXQOQxkVBFZqa2A1vptyy5I6Lc/vLN8vElCSHI0aVY+5ozbOWkJZi5E62+RXq4uZJSmqUYYCakOD1rGRLxXfrbTFIh00O9UYb7KpA+nUOL9z6P9oAScDF97txvFebq61lHWG3E6F85tGSIWTOseuE9wZTIZ894BJdjSwrKbSCosa3k12qCJ0BpxfEzCy7nRF9oKFdYighTl7wozMhYJy15lJrUHeZFOQ1Hl4fufZUny3pjtmFAI0qp1gaxVlLVDqDDy/JtbdTnspueRcyLKOfa2SE5BiLhSItNzeZWuKN9nB3S4n5vm1zzbOxiAtBa9ZacyKv9uuF1sUgllTuGWqUg3zJjunDekc6w4x5yDHqioRAPZgFzW+m6zTRzvNbb1dnKZJAqUawrCQ8tBQWyRxQS1EFodUx8pbQ7vJDoGlzqmJz7Jmi4ETll15bUfN6JTka543eX+/y6mQfu3CuKIpg2fd3bltzKnCu0HUXFx2XpwOOqwGeJO3u11Oa3LtbD2MZbQl+FcOO7/TQH+fkqkpKsTiYu34BWt6N3m72OU8TL/nf51uUgjzkAgUFoiZiKEdcZ5YCzIF452oY9yoGd7kR8MBxph+Z4kSIaClBOKI8an20lMtlnwyzHYiqF8Tnadsjjk2JsUC5SEjYBg9UCRAwrFdNkvnna3VkR/a6XIGql8TMmZKAJSLc8mBtRgK2RLEIGaRcGl5y++mmt9NPt3o8piofoiWCMUUNDagW7v7nWp4N/nZF7v821fTSD3FMpbYv5rZEYcipdh4buTZKLOh57ZeWpO7yT/QZpcmXozFGGFMp5ggdR16kWMXJEIMKWQH485cUM3uJj/7XpcmUE20o9l5zs4APmI9oriek93hrE07Lcga2k3lTEtdmuhiCo2zAqpHeWRo/ocwlQC7FVUUM+7UzmpgN5UPudKls0kstrmBhUMj9mqOTf5zyupIrkJm2OGS1AxvKmff6HKOdZzIqYQiLGEfiyJre7rWxG4q597n0oSpCZyAwTEIwahjFZZEhbkAs0oUgDvPs9ZI5QOuc2lCznGs7pyfQbDbNX9HQs64I6YxOlCn8FDzu6mceZnL06+mqw13nIJdgSVmT3Fsd6PuEHhKWYQRMjZvMNfgbirn2+bShMiULHsAu4MnulvEMRChJSlA8aFj9napIdfMbiofbptLEzCxJ97BYcodpmPIBxjrXNiKBjOMtDQVfa5B3lQ+zDaXNlqKtnCsW+WwWOehS7lRYtecc3TiuT1peILwLh9km8vXf3oyPVbDlFmQuMRGF5GhJwuRh8O/i/Ez2pE9rgneDB9qm0sTL2LyGHmO8kE2Lz5k5oUUS1sJGHM4aBrpxDXBmw8SvM9p5m1iF0uKscAv6JNYhir9jLGwk2L9FImSdt7rXIfewXafxcvbhEuWmBgLipPHpMTQo6ZYuYEFeFfuby8BXKO7uUF3n8nj29T8HTBlRqKYk4hC4NhMVNCFQRkgnBLtIkuuKd4M0h67pzH/to2bIikbY/Ew44MNvb4EOcVOaApAqee2KsE1wpuh7cqd0hXcdXDFOg+RYrTbGTcUZubkDAWpSDSpmyhrbjfD/e2405mFz+IDYSZMUGJ9pQBQRyzW7G5u2N0fezcu5pETK1LQOrRzWeea2M0Hid1nwBI2r/CuO2oxA22Qs+DYlBtrXHXELRJS527HNaib90DdJ+4/thGKJ98tFLJoQuQhyDFLoeSG2dxy/KBOhLVswmkT7vR24V7WzclZQS1G/8sQATcWhSfkQCcRxURgJ9RaMWHbiTu5X/jrKdQ4NogGsVYhxhWHnAEUuwiiMBdOebe28sI1m5txrhd3QrtwEzEkC88HsmB8YT602ZwSooAEL4kUHDuHTS2RGlj36e3CnUiVXEFZvSAjD8EAKKFYgOY18A7eEYM1r5uxo45O6xfuBLrLlmqec6YSzvfzRFrLJDzUnjunN6LzBQfDNu4msFsRPVT232UBRNdcdiKx/YRrWjfjbJ/udH7hp182fOcwNqOIhwE2Fx+amd/txY7FGKQUOwXakGsBhW2v7rT14iZOSC4SoIZAY7GN7e9J6hYUG+WYWmkXJ3BN6mZsG3VnKxc3EeNu713gWhQt7L5jTzZwohRlZyjhoG9DrlVUQ+4+cb34xefTMCkFyy4udSSDMzqawncIuMPuBJ2mjbJWUtThTp6oWtwEyGkHP8Bos4Whf4hqoXk3cBVJKQsCtwh2rjHdTIdqTqevF3/1t+k0HWqKPbsE0WvjoUsdQYZUAvOGCt6hYnEN6WY6OEx30nJxE6yrJxMiFQ+r+tBnSuAlZQLwmLK3TgW1BnUztQ27M5SLm1jRAj7JblCMVHho8JUQPZGELyS0RWl3/3HN6WZq23bnqRc3Q9rDI9qxIb0NqxZNDZ/7lGWIFgIgo6F4O23ONYKb6WwcyXZunobj6DySGqvN9GvMvTUh8vhr18FQcE3TZpr21U7r5T3hN1R6D6zWK9T2zU5r2W0ZIePYhg5Ng2siNnPbGjuPN7eJS8fD6j2mWo00GOwTe3BPGE0HFcI16Zp5Htg4YrVtU91oyhbsPZJaQvChebIzOGrbj8iGn0+HfcI1rJp5Ojd2HudsE9V7BNV7XrVa4LYTdWJ/bBOPjH9F3HlKNXuauW06ncUGe7oDSbjzmGrgNDfA6ZO7XdvHNByP9J5SrRZ4MtZ1KldrmxKGk530nkotE/jQ7NY5zKsnPIy094BqxSDTrtDJPao9CT4cUO9Z1VpB2t7PaYuLJ8zbufd8arEgbYfnbEXEE6a63HtQtYJouM4nrhWe8DlZ7znVokE6zZoT1QTbXIfDgfQeSy0U5FAv5vSVvzYzjKe6XpWhRjCzTDst5ynx9XT4cFSd51XjllnaZsoZanm9e+xgTL0aQw1VZrmfPvgxVuykV22oScosh2TEY7HVBHwmQZgiY+V0xk5ntwYqsx5Y0fWROvxiMVIA23ZedbLSbl/gmp/Mes+Gro+ZXqYuEJsmlDz2E+ROS6hGJ7NOOySPyZuqHtDBEs5l9wC7t9HW6kTbXaaPyNOoRTWBBkSJuTMszDUzmfeYyU/fbNfXN+tlvL63325ub9ZXi5ebxRfLm9Xixe33b6vXWacp6u4vPDw9FcSds7ZoIY9/9EDQGTD2VQNCfMHSGRGpicq8R1R+srxcXb1aL18vF99s128vV4uXXWFdB/yvv/XwjzhsT2FR1Bhvdkcb6V1nyCWph7OBJGaI26+45i3zHm/5P35YXS9eLqNW8uXydruK/9zcfrm5ncig6Wfc/r0Bjs4pjIEZKce2K3E1YG8hWFxDmnkP0vz0zfJqdbl4erm8vl6/Wvzhcvm2DlummuLubzzYkn13ZoLloB2UXTNyIFCXhLGi21AL9J5yLaD28M3P1rfXq7dvV4u/La82NzfrxRfb9fX1MbesyV8c+ajfP5NlEkwcMBfPKNSxoNQoZ95DOX/6/Xq7Xjz/Ky7+uFpe3eeB3P3Jgbf4FMDUTMVTJoQck53c6WfXJGc+SHL+avXDavuP28vLxfPnJ7uk9ZiiFOtQc6xXs92t6uExs2pyR1JUEu3MQNUwZ86dDtC7QaC6AySnsd0ramIGMoRYyiFDB5JgrARDESpWrDOlWROdeY/o3DuGX6xfh8Ja/GFzeble7X+6cvxBPBO3q8QMT4bYV1V4iDKZxSBJmChFWHrmm5rvzHt8572DeHcrWnyzXa6vJonqdKfwSXSHkqXdXsnwoYG3aquGPPMe5LlzBn+zXX97e7PqFSz1wefwB9Fd6pJKuGaNY6qvQSpxTXzmPeLzz8fwH5GmbSib5ujB89dJNMUoOZqCwdghlCWMvRQ0UQBpF8FyjXrmPdRzc/7+afvqzbpX5vTJ833/AxghtEdBNA9kSx5yl+XQfyIUw1HagTNyDX/mPfjz3QH8dLNdLb7cvN4svvntpCk3TdYHzuG5G+JJkrWFSzJGy9EQzNukVYOeOR8akjrnWO5ZINfZg/mRyZwxa2kXr3MNfObcW5fx2fffbjfri9V2dfFRT8MdEW2tt/awz71T+d+2638uP/arsdtuQ3QxyYTIrRKpsc+8h33eO5E/39xuX8eNKVbF/nO13asrTwvL9x3KsxTzHMtN1FjFdzDzkYgLeZJ4xBksc6eQVxOgeY8A3TmUd+WPb5bX16vLmXnzo27HH+QX4BpuW9bYKC3tJjiuCdG8R4j++VR+svmpDlanpYDBM/lOMSnsNrTjUKXWQDgB7H5DMazU3ppqGjTv0aCbI/kP2+XVd+uue/bhl+I5PXKCaqYhQApenIAIerulkms6NO/RoR/HpdhiSasSF0YvBtgmrBoJzXtI6LP70VoK9g4MoIVykUD0Dy10IpRksW6YWQnbvchcQ6G5gUKf2BTZfrVuCYPlHOjg2PI7FKVRij3gKH38H9dcaN7jQj/eyrQxlcQgGruvYtSjjboWWHuw6EdamTb2nDRLDkKVdVZfc82I5j1G9KMvTJsIJydxL9gr+9TgaN4DRz+qsrQpYAJXiJ1uDtZemWp0NO+hox95WdpUPUW1wwicqTNyVWOkeQ8j/UhO4IwBUVfJrOxCnZxVCyw/tLv+8ZSlLRsFmiOrxNqOzohvzZVmn85gPYaytBlDQlKXLOLm7Rlco6R5DyX9mMvSwURN7BnYCnBpN59zzZTmPab0IyxLm4ukLJmo7Ij37SWhBkvzHlj6/4eytBXAFOtfCWKRFLTHcE2a5j3S9OMoS8evJ2HOGSluHu2qRa4Z07zHmH70ZWkHjP2c2YGNJHfq0jWBmvcI1GeqS7ejFaNDCdYbiqvp0rxHl/5w9ecTDptab1SuJktzmXrEz1VoPt28s/WG52qQNJf77VYnrih3jPA6GFtveq7Ukqh0TVXnqRy3ruRhW7J1ZuikpkRzudc7ddYS8Skj7QzXSY2L5tIYpU5VC26nm/JpA6k1TbnHCHXGqm+bTsaD7L2XtXAp57M8tcMMOBxJZ1xQarSzwCFr0689VQwpIEPGpRjnQrR7BPcES9kksUZZRAAMS1MgkJryvB/6uYpAvdHPeyIOVBDl2FzEYHtwv/5kkWmKFnSQoUOzt+HmOtxDgKGzVAtOOGlknaFKqTHOAvf2Es9Vy2yDHM86nUFLqeHNsseqfqSptTN+KTXAWfYI1WcvxHeGkUZ1Wmf8Umpos4B+2MbKCVVoZxxTakaz7CGpP+YjsTOPKTWLWRra9IlLjCe8tHZmMKXGLAv4YxCWnbFLwYlSOTTL92srldmiWCe0Wong/X6nM5R729wgo7mhM4YpNTRZ9ujQH7jOeboc6B0YlNSkZMFfo9t2uql779TApEYkC34o4/gJn1yn7CU1D1lQzleJbiMZPr68U+qSGm8sOHUefcRVV++Ut6RmFwse8hk9kqqr9+pcNbhYsLfg4uOuunqvFlTDiQXvtxJ9tFVX75WAaiSx7IGXH3Fp0nsloppMLPSr9LCaIH34aXZ4U1LDiIUaQ9BHqJK9VwipQcOyR1V+TM0A75U/aqqw0OMEIHqv6FGThWUPmPyR4za9V+io4cJCj7bQ4b1CR40cFnoUhQ7vFTpqsLDMw5M/cmXVK3/UvGHZgyc/GmXVK4bU2GGh8ngrBt6riNT8YeGPrDczF1HvidUKg7vzXR97Xbv0qh41mFj4sfdeSq/uUSOKhe/pvTyC0k7p1UBqYLHsUZg/+sJB6RVCal6x8CGu4setF0uvJlJDi4Xv9wd/tBfr0quF1ABjaYDMH237pfRKIDXIWPgxtF9Kr95RY4uFuwNSH3Xht/SKGzW8WOTeIajH0ZoovQJHTTWWPUjzoyzilF7to+Ybi9CjKOKXXq2jhhuLnG946YSXzNIrbdR0Y5FDQ0qP5JJZegWPmnMs0lsM9XFfMkuv0lGDjkU++BTS6S6ZpVf/qKHHsgdyfsQl/NKrgtQcZJFfg054wttLryJSc49FPuAA9wnv171aSA08Fv1YLbpzofUeWq1KGpbzR1v3RuhVQmqEsej9NMGPuPCN0KuB1Mxi0UchSg6EUqsSfeSqBKFX0KnJw6KPT5Yg9Ao7NVRY9BHrEoReeaeGCYv+fyFMEHrVnhoeLL8KN/l0ygShVwOq8cGij1KaIPSqQjUlWA6SkT9ubYLQKw3VbGDJ54fEnLAHhdCrAtXYX9nDHX/ktVWEXsGnxvpK5sert3pFoJraK/dTix9BY21HWG+irMm9sscmfpxTTQi9ElHN6JU9PvFjKZ8j9GpENZNXGvbwR3on6JWDasau5MfQqkHolXtqfq7kQ6MyH/uoJ0Kv0lOTcmWGDvyRy/9ewacG44pNqyKP4d4W1Z7//f8A\", BinaryEncoding.Base64), Compression.Deflate))),",
                "    Typed = Table.TransformColumnTypes(Source, {{\"product_id\", Int64.Type}, {\"order_id\", Int64.Type}, {\"name\", type text}, {\"price\", type number}, {\"brand\", type text}, {\"stock_quatity\", Int64.Type}, {\"currency\", type text}, {\"price_usd\", type number}, {\"allocation_weight\", type number}, {\"allocated_order_value_usd\", type number}})",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "refunds",
        "description": "Order-level refund requests; currency inherited from matching order. Period filtering follows order date.",
        "lineageTag": "87c79edc-ab69-4c71-bf40-36f2ef03fccd",
        "columns": [
          {
            "name": "order_id",
            "dataType": "int64",
            "sourceColumn": "order_id",
            "summarizeBy": "none",
            "lineageTag": "500677d2-b07c-4716-adce-333f94ee8c59",
            "isHidden": true
          },
          {
            "name": "customer_id",
            "dataType": "int64",
            "sourceColumn": "customer_id",
            "summarizeBy": "none",
            "lineageTag": "6cf71721-0f01-4e78-8f4a-d22c29c194cb",
            "isHidden": true
          },
          {
            "name": "refund_date",
            "dataType": "dateTime",
            "sourceColumn": "refund_date",
            "summarizeBy": "none",
            "lineageTag": "f825f286-1386-4fb5-888d-44e1429e5d62",
            "formatString": "dd MMM yyyy"
          },
          {
            "name": "refund_amount",
            "dataType": "double",
            "sourceColumn": "refund_amount",
            "summarizeBy": "sum",
            "lineageTag": "d8c85b69-0233-4398-869f-e1f0d2c2c6ba",
            "isHidden": true
          },
          {
            "name": "refund_reason",
            "dataType": "string",
            "sourceColumn": "refund_reason",
            "summarizeBy": "none",
            "lineageTag": "94fd0df3-b6a8-4aea-b7d1-ab83a349d1c3"
          },
          {
            "name": "refund_status",
            "dataType": "string",
            "sourceColumn": "refund_status",
            "summarizeBy": "none",
            "lineageTag": "ed6afa1c-52a0-4d9f-a85c-45ca6682d1a3"
          },
          {
            "name": "payment_method",
            "dataType": "string",
            "sourceColumn": "payment_method",
            "summarizeBy": "none",
            "lineageTag": "da1e2c82-73c6-40a7-b523-9efaafd84d75"
          },
          {
            "name": "currency",
            "dataType": "string",
            "sourceColumn": "currency",
            "summarizeBy": "none",
            "lineageTag": "e2ec5456-400d-4c6e-8747-f6ebd26b4832"
          },
          {
            "name": "refund_amount_usd",
            "dataType": "double",
            "sourceColumn": "refund_amount_usd",
            "summarizeBy": "sum",
            "lineageTag": "a01f48a7-e775-4c13-9f55-f65fc0bc6179"
          }
        ],
        "partitions": [
          {
            "name": "refunds",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRecords(Json.Document(Binary.Decompress(Binary.FromText(\"rZhvb9s2EIe/iqDXscA7/ve7Ni2Kdl3hJSi6YRgCTmIcFZZkUFQ2b+h3H+zFXc3ynDjzS1uAzcd39+Nz/vXvcgiNDzdtU87hoqynMQ7dw2sFF2Xwt1Pf3DQu+nJeIkM+YzADWX595Lph6mM5B2sra7++Hbwbh76cl2+j74rGdW7pm2LoCxdCe+9W/33AGF2cxnJeLsJQ+3H0TXlRrt2m83286Xy8G5pyXl4G37SxuHRh+7ieQvB9vSnn5cfrV+lhbqax2R/oy8W3iJgiYh4RZyyDyAnET2Hol8XY/uWL4Gvf3u8QTsJbuM1i96N8Q3b5giBDIyrFmJIKFEdQRh5S8pSSU5TIvqdEgvJyWA2h6Nqxc7G+ywH6vmn75UnV+/HnD0T1dMWlsiC5NhYsAzxkFCmjyDPyGWQYQeYZ37voi8av2nsfNmdr0XeLXwjIioHiUnKBgIyBSiBlCikpSMy0qyAKuQhDM9Wx6IdYuLFo/FiH9vdsz175z76OT2/Z1x+v8qRSYyUtEwolcKFZ0rEqBVV5UJGdSxTHosff+jq29/5s5Xx59T4PKUxlGVNWKyO4AThk1CmjphjBZDqWYLzepk4chmLs3OrkVM3GzgeiWxErLkBJJgRnSgilDgFNCmjygHLG8HtASXTrT5NbtXGz69bRxXa8dXUc8tP5jAAiO1YZXQEwI6RAbhDNIaxNYS0Fm70sTR721bRetfU2hHbfdLaWffNyQdRU8koKDdqgBs0hmUtgCaZmeUw1Y/D0C3OfQDsX8M1eD86GSxZVSFMxzZi2inEAk+QtpAqkCQVS2apSObSb0Ye09X+u94n6vyeVVJ9/D5Kwpe6jCffRJ5Xy+q5dr9t+ub01XW4oj10hZAGfrT6Quo8m3EdnveC4+zyUcLwb/ujP1qvPNiBIFUgTCqSzmkfl7aMKRIdsrkdJ9+GVAZBMI1orOBNWJ3ip/GhCfkzWCY6uI107jtuevQ1Dd+akJaMH0VYMLQeuDQrgyeUJqQJpQoFM/kIhhHaftOdO2B+uPuUxWQVgwChjmDUKjeBpXVMP0oQH2WwOUVK7q+t2QJ+7gZGoL15TCyZXFQjBQRoFwBlLBzQVIk0Ikc2XFB8xvpULy5zVnirt9AaNmWskFR9NiI/N7iSPGcETdpIzG5DkvNLWoOGowDBM5hJTAzJ5AwKWX02O/itybDU5p8tysbU8q6xSFrWS9stv/wA=\", BinaryEncoding.Base64), Compression.Deflate))),",
                "    Typed = Table.TransformColumnTypes(Source, {{\"order_id\", Int64.Type}, {\"customer_id\", Int64.Type}, {\"refund_date\", type date}, {\"refund_amount\", type number}, {\"refund_reason\", type text}, {\"refund_status\", type text}, {\"payment_method\", type text}, {\"currency\", type text}, {\"refund_amount_usd\", type number}})",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "Calendar",
        "description": "Calendar dates for 2023 order-cohort analysis.",
        "lineageTag": "027b6081-d9e8-446b-bc8d-ea4717ca870f",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "lineageTag": "75430212-1952-4d3a-97fa-0e3aacd97784",
            "formatString": "dd MMM yyyy",
            "isKey": true
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "summarizeBy": "none",
            "lineageTag": "a46cdebd-6343-494a-b3a7-7eed550aee27"
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month",
            "summarizeBy": "none",
            "lineageTag": "226474e3-afd0-4afd-b638-5cfd695010f8",
            "sortByColumn": "MonthNo"
          },
          {
            "name": "MonthNo",
            "dataType": "int64",
            "sourceColumn": "MonthNo",
            "summarizeBy": "none",
            "lineageTag": "e08449af-c780-431b-a502-a1660c192a3f"
          },
          {
            "name": "Year Month",
            "dataType": "string",
            "sourceColumn": "Year Month",
            "summarizeBy": "none",
            "lineageTag": "510cf8cc-6ca0-46a8-970e-b40c44be5c00"
          }
        ],
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRecords(Json.Document(Binary.Decompress(Binary.FromText(\"td3NahRBAEXhV5FeJzBVPf87IbgQEheuRFyMMuhCkhASQcR3FzHCDKlTi3tvLY3mW/WR2031zMdf09Xh8Tjtp7qo8+WiXC7KdDF9OB4epv3fH11M13e3j9+m/fT2cDs9/+nmbtqXf//q1f+/fv796ffFS7LmyTlPLvPkKk+u8+QmT27z5C5OlkWezNdT8vWUfD0lX0/J11Py9ZR8PSVfT8nXU/P11Hw9NV9PzddT8/XUfD01X0/N11Pz9dR8PXO+njldT+Ux+Ob4+ZSsTbI2SQrSIClIg6QgDZKCNEgK0iApSIOkIA2SgtRJHIMGma8Hx6BB5uvBMWiQ+XpwDBpkvh4cgwaZrwfHoEHm68ExaJD5enAMGmS+HhyDBpmvB8egSs68ia4PD6fk3CTnJknXpUHSdWmQdF0aJF2XBknXpUHSdWmQdF0aJP2vrpO4iQwyXw9uIoPM14ObyCDz9eAmMsh8PbiJDDJfD24ig8zXg5vIIPP14CYyyHw9uIkMMl8PbiKDzNeDD8gMMl3Pksfg6/szctkkl02SgjRICtIgKUiDpCANkoI0SArSIClIg6QgdRLHoEHm68ExaJD5enAMGmS+HhyDBpmvB8egQebrwTFokPl6cAwaZL4eHIMGma8Hx6BB5uvBMWiQ+XpwDKrkqvcY7+cpuWqSqybJt1IyybdSMsm3UjLJt1IyybdSMsm3UjLJt1IyybdSKtl5jCeT+Xo6j/FkMl9P5zGeTObr6TzGk8l8PZ3HeDKZr6fzGE8m8/V0HuPJZL6ezmM8mczX03mMJ5P5ejqP8WQyX0/nMZ5MputZd156eDo7OrdukusmiQdPdRIPnuokHjzVSTx4qpN48FQn8eCpTuLBU53Eg6cyyS896GS+Hn7pQSfz9fBLDzqZr4dfetDJfD380oNO5uvhlx50Ml8Pv/Sgk/l6+KUHnczXwy896GS+Hn7pQSfz9fBLDyK56S2376fkpklumiTXI5Ncj0xyPTLJ9cgk1yOTXI9Mcj0yyfWoZGe5yWS+ns5yk8l8PZ3lJpP5ejrLTSbz9XSWm0zm6+ksN5nM19NZbjKZr6ez3GQyX09nuclkvp7OcpPJfD2d5SaT6Xq2ndN4T19PyW2T3DZJPBGhk3giQifxRIRO4okIncQTETqJJyJ0Ek9E6CSeiJBJPo2nk/l6+DSeTubr4dN4Opmvh0/j6WS+Hj6Np5P5evg0nk7m6+HTeDqZr4dP4+lkvh4+jaeT+Xr4NJ5O5uvh03g6ma5nx2Pw/fH+lNw1yV2TpCANkoI0SArSIClIg6QgDZKCNEgK0iApSJ3EMWiQ+XpwDBpkvh4cgwaZrwfHoEHm68ExaJD5enAMGmS+HhyDBpmvB8egQebrwTFokPl6cAwaZL4eHIMiWRa83N59eTwly6JllkXTpHwck/pxTArIMakgx6SEHJMackyKyDGpIsPECeeYAzrCEeeYAzrCGeeYAzrCIeeYAzrCKeeYAzrCMeeYAzrCOeeYAzrCQeeYAzrCSeeYAzrCUeeYAzrCWeeY8Y46X1dxc/fjzGx+6nF5+anHpfN9FY5JbTomtemY1KZjUpuOSW06JrXpmNSmYeJWdMwBHeFWdMwBHeFWdMwBHeFWdMwBHeFWdMwBHeFWdMwBHeFWdMwBHeFWdMwBHeFWdMwBHeFWdMwBHeFWlM3ON09cHb+cmc1Pbi4vP7m5dL56wjGpI8ekjhyTOnJM6sgxqSPHpI4ckzoyTNx1jjmgI9x1jjmgI9x1jjmgI9x1jjmgI9x1jjmgI9x1jjmgI9x1jjmgI9x1jjmgI9x1jjmgI9x1jjmgI9x1jml39OkP\", BinaryEncoding.Base64), Compression.Deflate))),",
                "    Typed = Table.TransformColumnTypes(Source, {{\"Date\", type date}, {\"Year\", Int64.Type}, {\"Month\", type text}, {\"MonthNo\", Int64.Type}, {\"Year Month\", type text}})",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "Segments",
        "description": "Dynamic segments within the current selection.",
        "lineageTag": "d90fb769-ce3d-4c1b-ba1b-3e8378c00d5d",
        "columns": [
          {
            "name": "Segment",
            "dataType": "string",
            "sourceColumn": "Segment",
            "summarizeBy": "none",
            "lineageTag": "f444237d-4c01-462b-9702-dab1eec97dd3"
          }
        ],
        "partitions": [
          {
            "name": "Segments",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRecords(Json.Document(Binary.Decompress(Binary.FromText(\"i65WCk5Nz03NK1GyUvLPS9UtycxNVUgqrUwtKlaq1UGWDUotSE0sgcvFAgA=\", BinaryEncoding.Base64), Compression.Deflate))),",
                "    Typed = Table.TransformColumnTypes(Source, {{\"Segment\", type text}})",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "FX Snapshot",
        "description": "Rates by ExchangeRate-API. HRK uses the fixed ECB HRK/EUR rate then current EUR/USD. Snapshot only; do not redistribute as a rates dataset.",
        "lineageTag": "8a70e1f5-e727-4743-99fe-44d6c8ce5a63",
        "columns": [
          {
            "name": "Currency",
            "dataType": "string",
            "sourceColumn": "Currency",
            "summarizeBy": "none",
            "lineageTag": "1e79d9b6-b01a-4225-9d1b-d74af049d36c"
          },
          {
            "name": "Units per USD",
            "dataType": "double",
            "sourceColumn": "Units per USD",
            "summarizeBy": "sum",
            "lineageTag": "2d71f81e-5d74-4276-8409-a3a059a1015a"
          },
          {
            "name": "USD per unit",
            "dataType": "double",
            "sourceColumn": "USD per unit",
            "summarizeBy": "sum",
            "lineageTag": "946d6dce-984e-440d-9c17-cf8165165afb"
          },
          {
            "name": "Rate date UTC",
            "dataType": "string",
            "sourceColumn": "Rate date UTC",
            "summarizeBy": "none",
            "lineageTag": "c3763113-6463-42b2-927b-c1d0db3b8aee"
          },
          {
            "name": "Rate date Chicago",
            "dataType": "string",
            "sourceColumn": "Rate date Chicago",
            "summarizeBy": "none",
            "lineageTag": "c6ea4b9d-544c-4613-aec1-00668ed5a613"
          }
        ],
        "partitions": [
          {
            "name": "FX Snapshot",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRecords(Json.Document(Binary.Decompress(Binary.FromText(\"rZdPT2RVEMW/Cnlr5qZO/S920CAoDEOaaR3HuJiMRNmgQWZhjN/dPN2MvnLl7QWLbpL7y7mn6pz73e/L7tPz88PTx9+Wk+X04nw5Xg5Pjy+/Hv3y8Hx0uD9fTmR4sB0vh/vzv7789PT4spzQ4GAupQgnSTDkeNl/eHk4+mH9c3i7W04WJvZXVK9Yls9/3P30+PHDjz9//g+8/HH8T5T9/RYFBhmeklsaInInlypzV8pInctzaKTB0PVIbHECIKlEGDIUPJXlbH+zZbEBMCq2LChzkMPgDKHMqTC70/8QxlSlFcZQyiklYXN12d3cbVFKYySzuHamAZmREcE8qpQnA91+uwXyERDt7kmzTNndAiZqcw28e9OII0w0kELej5SANRksnClc4lORzq+vO3mMIevEbPQxERUJF2IUaq4+F5eNPobhZqoNDaHEilS1RBBpc8fq4rDf4tDIEKaNdzCgxiTJBRJjwVSWy7NGGhqhJbzxDYaIGhcF1lioyShXXSxgmCnSm1tKN81AMTtl8txLutr3Bo5CJBRNaq7br9Q9lSxJaG5qfnnbuKZsuEZ225hAakbIFCXxtLk4X901+w8WQ2GKZgUSuRg7otgzyIRsKtD1RWcfrqEm0QpEEazhXqkF1ck4+28aHDEZQWJdRhBRSAYUYUnErnMdfdONepYRtSwEIASpYmGKmsryumsWNUxDrbkqkIZUhTNRJc+NqtfvbpubisEpTk3/I1sTQSBMnuI1d65uLzsa4RwS4Oh4iMI4CZbO5RlzbXP7vi2BoR5cWxoL1ko3QXlhclO/u2jEkVUZiablcLlDHRmgJJ8bV3dXzTg5rwmh1pYKqyhPB+CuWXNdfHfTShPrmQ0Nu3AVyJk0TedKsz+cNZtGByKYGs8QkFFBBIYnMc11zf1pk5wyonv4+r8+c0Eumk5RI2VNom7rIRgKUJkXYW5Avb1t5ppHqUg1bUukQsVhGRHQtahOhFkP3y6ZTf+ceubXXWFIk6FVbV0AAq4Blsgo+FyXvnvzRfNICR5JXJ09iBC6NoU1GEv/fspMBHrfjQ188GrH7sXt8EKF1PqurP9rkO//BA==\", BinaryEncoding.Base64), Compression.Deflate))),",
                "    Typed = Table.TransformColumnTypes(Source, {{\"Currency\", type text}, {\"Units per USD\", type number}, {\"USD per unit\", type number}, {\"Rate date UTC\", type text}, {\"Rate date Chicago\", type text}})",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "measures (2)",
        "description": "Executive report measures.",
        "lineageTag": "34ca8452-f4ce-4eb4-a8ed-b766ea2fcdc2",
        "columns": [
          {
            "name": "_placeholder",
            "dataType": "double",
            "sourceColumn": "_placeholder",
            "summarizeBy": "sum",
            "lineageTag": "0c7a0ba5-279a-42f9-859f-ebe5c4d240d3",
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "measures (2)",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRecords(Json.Document(Binary.Decompress(Binary.FromText(\"i65Wii/ISUxOzcjPSUktUrIyrI0FAA==\", BinaryEncoding.Base64), Compression.Deflate))),",
                "    Typed = Table.TransformColumnTypes(Source, {{\"_placeholder\", type number}})",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Order Value USD",
            "expression": [
              "SUM(products[allocated_order_value_usd])"
            ],
            "formatString": "$#,0.00;($#,0.00);$0.00",
            "description": "Order totals converted at the dated FX snapshot, allocated to lines by relative line price. Additive across brands; not recognized revenue or historical FX.",
            "lineageTag": "6b66a939-828d-4c32-9d10-51a09afdefaa"
          },
          {
            "name": "Orders",
            "expression": [
              "DISTINCTCOUNT(products[order_id])"
            ],
            "formatString": "#,0",
            "description": "",
            "lineageTag": "74e96c21-d61c-4b53-b2fd-b09c280260e8"
          },
          {
            "name": "Order Lines",
            "expression": [
              "COUNTROWS(products)"
            ],
            "formatString": "#,0",
            "description": "Count of source product rows, not units sold.",
            "lineageTag": "6e05c901-3f95-4d45-96d6-ee4878f8d2b0"
          },
          {
            "name": "Average Order Value USD",
            "expression": [
              "DIVIDE([Order Value USD], [Orders])"
            ],
            "formatString": "$#,0.00;($#,0.00);$0.00",
            "description": "Allocated order value divided by distinct orders in the same filter context.",
            "lineageTag": "b6b497af-d386-4d68-96c9-d73d69529a07"
          },
          {
            "name": "Purchasing Customers",
            "expression": [
              "VAR ids = VALUES(products[order_id]) RETURN CALCULATE(DISTINCTCOUNT(orders[customer_id]), KEEPFILTERS(TREATAS(ids, orders[order_id])))"
            ],
            "formatString": "#,0",
            "description": "",
            "lineageTag": "59403f97-7f85-451c-966f-e7bd812c8c6a"
          },
          {
            "name": "Repeat Buyers",
            "expression": [
              "VAR ids = VALUES(products[order_id])",
              "VAR t = CALCULATETABLE(SUMMARIZE(orders, orders[customer_id], \"n\", COUNTROWS(orders)), KEEPFILTERS(TREATAS(ids, orders[order_id])))",
              "RETURN COUNTROWS(FILTER(t, [n] > 1))"
            ],
            "formatString": "#,0",
            "description": "",
            "lineageTag": "38d2e2e6-5bd8-42ed-ba7f-d64e1b276ffd"
          },
          {
            "name": "One-time Buyers",
            "expression": [
              "[Purchasing Customers] - [Repeat Buyers]"
            ],
            "formatString": "#,0",
            "description": "",
            "lineageTag": "8d4651c8-34f4-438e-9191-3e893c352531"
          },
          {
            "name": "Repeat Buyer Rate",
            "expression": [
              "DIVIDE([Repeat Buyers], [Purchasing Customers])"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "description": "Share of purchasing customers with more than one selected order; not a cohort retention rate.",
            "lineageTag": "8862049d-a687-4257-aa5b-a7f47fd0254c"
          },
          {
            "name": "Segment Customers",
            "expression": [
              "SWITCH(SELECTEDVALUE(Segments[Segment]), \"One-time buyers\", [One-time Buyers], \"Repeat buyers\", [Repeat Buyers])"
            ],
            "formatString": "#,0",
            "description": "",
            "lineageTag": "ece2ecf6-2247-4dab-b23b-b4854adc1abe"
          },
          {
            "name": "Customer Records",
            "expression": [
              "COUNTROWS(customers)"
            ],
            "formatString": "#,0",
            "description": "Customer master records; independent of order date, brand and order currency.",
            "lineageTag": "31155867-3b26-4918-8102-8c4b7032c4ee"
          },
          {
            "name": "Customer Rank",
            "expression": [
              "IF(NOT ISBLANK([Order Value USD]), RANKX(ALLSELECTED(customers[name]), [Order Value USD], , DESC, Dense))"
            ],
            "formatString": "#,0",
            "description": "",
            "lineageTag": "74b24fd3-e376-4ec2-8eb4-5b754fdbf0e9"
          },
          {
            "name": "Brand Rank",
            "expression": [
              "IF(NOT ISBLANK([Order Value USD]), RANKX(ALLSELECTED(products[brand]), [Order Value USD], , DESC, Dense))"
            ],
            "formatString": "#,0",
            "description": "",
            "lineageTag": "618d892d-9fac-47ad-af98-67c46bbffbcf"
          },
          {
            "name": "Country Share",
            "expression": [
              "DIVIDE([Order Value USD], CALCULATE([Order Value USD], ALLSELECTED(customers[country])))"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "description": "",
            "lineageTag": "650686ca-1b41-4011-831c-997dc14fea28"
          },
          {
            "name": "Refund Requests",
            "expression": [
              "VAR ids=VALUES(products[order_id]) RETURN CALCULATE(DISTINCTCOUNT(refunds[order_id]), KEEPFILTERS(TREATAS(ids, refunds[order_id])))"
            ],
            "formatString": "#,0",
            "description": "",
            "lineageTag": "6d2c139f-b6cf-4c54-ab9f-36572b27220c"
          },
          {
            "name": "Processed Requests",
            "expression": [
              "CALCULATE([Refund Requests], KEEPFILTERS(refunds[refund_status]=\"Processed\"))"
            ],
            "formatString": "#,0",
            "description": "",
            "lineageTag": "83f9d786-5276-4ce3-8807-b745cdcd127c"
          },
          {
            "name": "Pending Requests",
            "expression": [
              "CALCULATE([Refund Requests], KEEPFILTERS(refunds[refund_status]=\"Pending\"))"
            ],
            "formatString": "#,0",
            "description": "",
            "lineageTag": "17520c58-6912-49fd-a61c-37c60c10d53a"
          },
          {
            "name": "Rejected Requests",
            "expression": [
              "CALCULATE([Refund Requests], KEEPFILTERS(refunds[refund_status]=\"Rejected\"))"
            ],
            "formatString": "#,0",
            "description": "",
            "lineageTag": "f9ec39a6-e501-49e2-a7b6-ef7f9978a6be"
          },
          {
            "name": "Refund Request Rate",
            "expression": [
              "DIVIDE([Refund Requests],[Orders])"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "description": "Distinct selected orders with any refund request / selected orders. Includes processed, pending and rejected requests.",
            "lineageTag": "50794fed-0419-489d-8763-8115ab860faf"
          },
          {
            "name": "Processed Refund Rate",
            "expression": [
              "DIVIDE([Processed Requests],[Orders])"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "description": "",
            "lineageTag": "efa69744-a70f-4869-90fc-13bc85460222"
          },
          {
            "name": "Requested Refund USD",
            "expression": [
              "VAR ids=VALUES(products[order_id]) RETURN CALCULATE(SUM(refunds[refund_amount_usd]), KEEPFILTERS(TREATAS(ids, refunds[order_id])))"
            ],
            "formatString": "$#,0.00;($#,0.00);$0.00",
            "description": "Order-level requested amount at current FX, including all statuses. Not attributed to a returned product.",
            "lineageTag": "980e2e28-a1bd-4efe-819e-11bfd5521342"
          },
          {
            "name": "Processed Refund USD",
            "expression": [
              "CALCULATE([Requested Refund USD], KEEPFILTERS(refunds[refund_status]=\"Processed\"))"
            ],
            "formatString": "$#,0.00;($#,0.00);$0.00",
            "description": "",
            "lineageTag": "92326e75-a3d5-460d-a690-37df2bd3119f"
          },
          {
            "name": "Pending Refund USD",
            "expression": [
              "CALCULATE([Requested Refund USD], KEEPFILTERS(refunds[refund_status]=\"Pending\"))"
            ],
            "formatString": "$#,0.00;($#,0.00);$0.00",
            "description": "",
            "lineageTag": "19445037-ac54-4dac-a739-b967c3fa7f98"
          },
          {
            "name": "Prior Month Value USD",
            "expression": [
              "VAR hasCurrent=NOT ISBLANK([Order Value USD])",
              "VAR _priorValue=CALCULATE([Order Value USD], DATEADD('Calendar'[Date], -1, MONTH))",
              "RETURN IF(hasCurrent, _priorValue)"
            ],
            "formatString": "$#,0.00;($#,0.00);$0.00",
            "description": "",
            "lineageTag": "0a853dee-713d-4eea-85f9-6d810be8da42"
          },
          {
            "name": "Monthly Change",
            "expression": [
              "DIVIDE([Order Value USD]-[Prior Month Value USD], [Prior Month Value USD])"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "description": "",
            "lineageTag": "40d93543-758d-413b-abc5-0a85592cc6d9"
          },
          {
            "name": "Latest Month Value USD",
            "expression": [
              "VAR _endDate=MAX('Calendar'[Date])",
              "VAR _startDate=DATE(YEAR(_endDate),MONTH(_endDate),1)",
              "RETURN CALCULATE([Order Value USD], REMOVEFILTERS('Calendar'), DATESBETWEEN('Calendar'[Date],_startDate,_endDate))"
            ],
            "formatString": "$#,0.00;($#,0.00);$0.00",
            "description": "",
            "lineageTag": "7d1bc4e9-8705-4da0-bb6c-75f5ee6f5904"
          },
          {
            "name": "Latest Prior Month Value USD",
            "expression": [
              "VAR _endDate=EOMONTH(MAX('Calendar'[Date]),-1)",
              "VAR _startDate=DATE(YEAR(_endDate),MONTH(_endDate),1)",
              "RETURN CALCULATE([Order Value USD], REMOVEFILTERS('Calendar'), DATESBETWEEN('Calendar'[Date],_startDate,_endDate))"
            ],
            "formatString": "$#,0.00;($#,0.00);$0.00",
            "description": "",
            "lineageTag": "67c92540-1665-42ec-b32d-c5401d348f96"
          },
          {
            "name": "Latest Month Change",
            "expression": [
              "DIVIDE([Latest Month Value USD]-[Latest Prior Month Value USD], [Latest Prior Month Value USD])"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "description": "",
            "lineageTag": "43317449-1add-4afb-b576-8a2b32959683"
          },
          {
            "name": "Delivered Orders",
            "expression": [
              "CALCULATE([Orders], KEEPFILTERS(orders[order_status]=\"Delivered\"))"
            ],
            "formatString": "#,0",
            "description": "",
            "lineageTag": "1ad7125c-729d-4f46-b290-3aeb5e1bf99f"
          },
          {
            "name": "Shipped Orders",
            "expression": [
              "CALCULATE([Orders], KEEPFILTERS(orders[order_status]=\"Shipped\"))"
            ],
            "formatString": "#,0",
            "description": "",
            "lineageTag": "d303c702-894e-41fe-b2e1-488c636bdcf4"
          },
          {
            "name": "Processing Orders",
            "expression": [
              "CALCULATE([Orders], KEEPFILTERS(orders[order_status]=\"Processing\"))"
            ],
            "formatString": "#,0",
            "description": "",
            "lineageTag": "65d3dfdb-9541-4421-a2d9-d1a367a72c20"
          },
          {
            "name": "Average Product Price USD",
            "expression": [
              "AVERAGE(products[price_usd])"
            ],
            "formatString": "$#,0.00;($#,0.00);$0.00",
            "description": "Assumes line prices are expressed in their order currency.",
            "lineageTag": "a6dd9d1e-9fd6-499d-855c-07e20c0469f3"
          },
          {
            "name": "Source Stock",
            "expression": [
              "MAX(products[stock_quatity])"
            ],
            "formatString": "#,0",
            "description": "Source stock value shown only at product-row level. Snapshot date and inventory grain are unverified; do not sum across order lines.",
            "lineageTag": "20fe0f48-23b8-4435-86c7-0f28ba9e39ba"
          },
          {
            "name": "Sales Takeaway",
            "expression": [
              "VAR v=[Order Value USD]",
              "VAR brandTable=TOPN(1, ADDCOLUMNS(ALLSELECTED(products[brand]), \"v\", [Order Value USD]), [v], DESC, products[brand], ASC)",
              "VAR leader=CONCATENATEX(brandTable,products[brand],\", \")",
              "RETURN IF(ISBLANK(v), \"No orders match the current filters.\", \"Leading brand: \" & leader & \". Review its allocated contribution and monthly pattern before changing assortment.\")"
            ],
            "formatString": "General",
            "description": "",
            "lineageTag": "e1b0151e-c07e-4a9b-91a7-8803ddd1e739"
          },
          {
            "name": "Geo Takeaway",
            "expression": [
              "VAR t=TOPN(1, ADDCOLUMNS(ALLSELECTED(customers[country]), \"v\", [Order Value USD]), [v], DESC, customers[country], ASC)",
              "VAR country=CONCATENATEX(t,customers[country],\", \")",
              "VAR share=DIVIDE(SUMX(t,[v]),CALCULATE([Order Value USD],ALLSELECTED(customers[country])))",
              "RETURN IF(ISBLANK([Order Value USD]),\"No orders match the current filters.\",country & \" leads with \" & FORMAT(share,\"0.0%\") & \" of selected order value. Review market concentration and the smaller markets.\")"
            ],
            "formatString": "General",
            "description": "",
            "lineageTag": "64b9c1e9-15f0-4d84-a75e-cb30c4e97347"
          },
          {
            "name": "Customer Takeaway",
            "expression": [
              "IF(ISBLANK([Orders]), \"No purchasing customers match the current filters.\", FORMAT([Repeat Buyers],\"#,0\") & \" of \" & FORMAT([Purchasing Customers],\"#,0\") & \" buyers placed more than one selected order (\" & FORMAT([Repeat Buyer Rate],\"0.0%\") & \"). Investigate repeat purchase opportunities; this is not a retention metric.\")"
            ],
            "formatString": "General",
            "description": "",
            "lineageTag": "90163446-e53e-4d39-b84b-32ee5be55cec"
          },
          {
            "name": "Refund Takeaway",
            "expression": [
              "FORMAT(COALESCE([Refund Requests],0),\"0\") & \" requests: \" & FORMAT(COALESCE([Processed Requests],0),\"0\") & \" processed, \" & FORMAT(COALESCE([Pending Requests],0),\"0\") & \" pending, \" & FORMAT(COALESCE([Rejected Requests],0),\"0\") & \" rejected. Investigate pending cases and the leading request reasons.\""
            ],
            "formatString": "General",
            "description": "",
            "lineageTag": "680278b8-5182-42d1-ae86-f5650d5b0113"
          },
          {
            "name": "Trend Takeaway",
            "expression": [
              "VAR prior=[Latest Prior Month Value USD]",
              "VAR thisMonth=FORMAT(MAX('Calendar'[Date]),\"MMM yyyy\")",
              "RETURN IF(ISBLANK(prior)||prior=0,\"No comparable prior month is available for \" & thisMonth & \".\",thisMonth & \" order value is \" & FORMAT([Latest Month Change],\"+0.0%;-0.0%;0.0%\") & \" versus the preceding month at the same FX snapshot. Investigate the underlying order mix.\")"
            ],
            "formatString": "General",
            "description": "",
            "lineageTag": "08cc5b0c-1e0c-48e1-8ba2-027b8b865c2f"
          },
          {
            "name": "Selection Context",
            "expression": [
              "\"Order period: \" & FORMAT(MIN('Calendar'[Date]),\"dd MMM yyyy\") & \" to \" & FORMAT(MAX('Calendar'[Date]),\"dd MMM yyyy\") & \" | USD at 22 Sep 2026 Chicago FX snapshot\""
            ],
            "formatString": "General",
            "description": "",
            "lineageTag": "4f3945c6-9b61-4f58-9fce-fa2784b4a08d"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "e41c1423-6897-4feb-9e81-998b3ee7875b",
        "fromTable": "orders",
        "fromColumn": "customer_id",
        "toTable": "customers",
        "toColumn": "id",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "f481853a-dc00-4f50-9c14-080983398f5e",
        "fromTable": "orders",
        "fromColumn": "order_date",
        "toTable": "Calendar",
        "toColumn": "Date",
        "crossFilteringBehavior": "oneDirection",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "2de55f55-4e85-4a4a-a1f6-669187ff3c01",
        "fromTable": "products",
        "fromColumn": "order_id",
        "toTable": "orders",
        "toColumn": "order_id",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "a5920745-edb2-4c14-9599-38fd16975aab",
        "fromTable": "refunds",
        "fromColumn": "order_id",
        "toTable": "orders",
        "toColumn": "order_id",
        "crossFilteringBehavior": "oneDirection"
      }
    ]
  }
}